### 데이터프레임(DataFrame) : 표 -> 대부분의 데이터를 다루는 형태
- 엑셀처럼 행 과 열로 된 표를 다루는 가장 기본 형태
- 수천, 수만줄의 데이터도 코드 몇줄로 다루는게 가능하다
- 데이터 분석이라는 것을 해보고 싶다 -> 꼭 해야 합니다.

#### 1. Series - 한줄짜리 데이터
- 리스트와 비슷하지만, 각 값마다 인덱스가 붙습니다.
- 표의 한 열을 나타낸다.

In [2]:
# 실습
import pandas as pd

data = [81,72,33,94] # 수학점수
data

[81, 72, 33, 94]

In [3]:
data_series = pd.Series(data)
data_series

0    81
1    72
2    33
3    94
dtype: int64

In [4]:
en_data = [92,88,67,54]
en_series = pd.Series(en_data)
en_series

0    92
1    88
2    67
3    54
dtype: int64

In [ ]:
data = {
      "이름": ["이현근", "김수연", "송수림", "장안나", "백성현", "김병주", "유종혁", "주승우"],
      "성별": ["남", "여", "여", "여", "남", "남", "남", "남"],
      "나이": [27, 27, 44, 31, 29, 35, 26, 40],
      "취미": ["코딩", "숨쉬기", "맛집탐방", "독서", "축구", "영화감상", "게임", "등산"],
      "키": [182, 161, 165, 158, 175, 170, 178, 183],
      "몸무게": [62, None, None, 50, 68, 72, 75, 80]
  }
df = pd.DataFrame(data)
df

{'이름': ['이현근', '김수연', '송수림'],
 '성별': ['남', '여', '여'],
 '나이': [27, 27, 44],
 '취미': ['코딩', '숨쉬기', '맛집탐방'],
 '키': [182, 161, 165],
 '몸무게': [62, None, None]}

In [8]:
df = pd.DataFrame(data)
df

    이름 성별  나이    취미    키   몸무게
0  이현근  남  27    코딩  182  62.0
1  김수연  여  27   숨쉬기  161   NaN
2  송수림  여  44  맛집탐방  165   NaN

In [9]:
data = {
      "이름": ["이현근", "김수연", "송수림", "장안나", "백성현", "김병주", "유종혁", "주승우"],
      "성별": ["남", "여", "여", "여", "남", "남", "남", "남"],
      "나이": [27, 27, 44, 31, 29, 35, 26, 40],
      "취미": ["코딩", "숨쉬기", "맛집탐방", "독서", "축구", "영화감상", "게임", "등산"],
      "키": [182, 161, 165, 158, 175, 170, 178, 183],
      "몸무게": [62, None, None, 50, 68, 72, 75, 80]
  }
df = pd.DataFrame(data)
df

    이름 성별  나이    취미    키   몸무게
0  이현근  남  27    코딩  182  62.0
1  김수연  여  27   숨쉬기  161   NaN
2  송수림  여  44  맛집탐방  165   NaN
3  장안나  여  31    독서  158  50.0
4  백성현  남  29    축구  175  68.0
5  김병주  남  35  영화감상  170  72.0
6  유종혁  남  26    게임  178  75.0
7  주승우  남  40    등산  183  80.0

### 3. 데이터의 형태를 확인
- 보통 데이터의 처음과 끝을 확인해볼 필요

In [10]:
df.head(3)

    이름 성별  나이    취미    키   몸무게
0  이현근  남  27    코딩  182  62.0
1  김수연  여  27   숨쉬기  161   NaN
2  송수림  여  44  맛집탐방  165   NaN

In [11]:
df.tail(3)

    이름 성별  나이    취미    키   몸무게
5  김병주  남  35  영화감상  170  72.0
6  유종혁  남  26    게임  178  75.0
7  주승우  남  40    등산  183  80.0

### 4. 표의 크기 - shape
- shape : 행과 열의 크기
- 괄호 없이 쓰는 - 메서드가 아니라 속성

In [12]:
df.shape

(8, 6)

#### 5. 전체 요약 정보 - info()
- 비어있지 않은 값의 개수를 한눈에 보기

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   성별      8 non-null      str
 2   나이      8 non-null      int64
 3   취미      8 non-null      str
 4   키       8 non-null      int64
 5   몸무게     6 non-null      float64
dtypes: float64(1), int64(2), str(3)
memory usage: 516.0 bytes

#### 6. 숫자 통계 요약 - describe()
- 숫자로 된 열의 평균, 최대, 최소 기본 통계값
- 문자열 섞여있는 열은 빠지는

In [14]:
df.describe()

              나이           키        몸무게
count   8.000000    8.000000   6.000000
mean   32.375000  171.500000  67.833333
std     6.674846    9.516902  10.666146
min    26.000000  158.000000  50.000000
25%    27.000000  164.000000  63.500000
50%    30.000000  172.500000  70.000000
75%    36.250000  179.000000  74.250000
max    44.000000  183.000000  80.000000

#### 7. 타입형태 - 각 열이 어떤 자료형인지 확인할 필요
- int64, float64, object(글자형) 보통

In [18]:
df.dtypes

이름         str
성별         str
나이       int64
취미         str
키        int64
몸무게    float64
dtype: object

#### 8. 열 이름 목록
- columns

In [20]:
df.columns

Index(['이름', '성별', '나이', '취미', '키', '몸무게'], dtype='str')

In [21]:
data = {
      "주문번호": [101, 102, 103, 104, 105, 106, 107, 108],
      "고객명": ["민지", "준호", "서연", "도윤", "하은", "지훈", "예린", "현우"],
      "메뉴": ["아메리카노", "카페라떼", "딸기스무디", "아메리카노", "녹차라떼", "카페라떼", "초코케이크", "아메리카노"],
      "수량": [2, 1, 1, 3, 1, 2, 1, 1],
      "가격": [4500, 5000, 5500, 4500, 5200, 5000, 6000, 4500],
      "회원여부": ["회원", "비회원", "회원", "회원", "비회원", "회원", "회원", "비회원"],
      "방문일": ["2026-09-01", "2026-09-01", "2026-09-02", "2026-09-02",
                "2026-09-03", "2026-09-03", "2026-09-04", "2026-09-04"],
      "리뷰점수": [5, None, 4, 5, 3, None, 5, 4]
  }

df = pd.DataFrame(data)

In [24]:
df

   주문번호 고객명     메뉴  수량    가격 회원여부         방문일  리뷰점수
0   101  민지  아메리카노   2  4500   회원  2026-09-01   5.0
1   102  준호   카페라떼   1  5000  비회원  2026-09-01   NaN
2   103  서연  딸기스무디   1  5500   회원  2026-09-02   4.0
3   104  도윤  아메리카노   3  4500   회원  2026-09-02   5.0
4   105  하은   녹차라떼   1  5200  비회원  2026-09-03   3.0
5   106  지훈   카페라떼   2  5000   회원  2026-09-03   NaN
6   107  예린  초코케이크   1  6000   회원  2026-09-04   5.0
7   108  현우  아메리카노   1  4500  비회원  2026-09-04   4.0

In [27]:
df.head(3)

   주문번호 고객명     메뉴  수량    가격 회원여부         방문일  리뷰점수
0   101  민지  아메리카노   2  4500   회원  2026-09-01   5.0
1   102  준호   카페라떼   1  5000  비회원  2026-09-01   NaN
2   103  서연  딸기스무디   1  5500   회원  2026-09-02   4.0

In [29]:
df.tail(3)

   주문번호 고객명     메뉴  수량    가격 회원여부         방문일  리뷰점수
5   106  지훈   카페라떼   2  5000   회원  2026-09-03   NaN
6   107  예린  초코케이크   1  6000   회원  2026-09-04   5.0
7   108  현우  아메리카노   1  4500  비회원  2026-09-04   4.0

In [31]:
df.shape

(8, 8)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문번호    8 non-null      int64
 1   고객명     8 non-null      str
 2   메뉴      8 non-null      str
 3   수량      8 non-null      int64
 4   가격      8 non-null      int64
 5   회원여부    8 non-null      str
 6   방문일     8 non-null      str
 7   리뷰점수    6 non-null      float64
dtypes: float64(1), int64(3), str(4)
memory usage: 644.0 bytes

In [35]:
df.describe

<bound method NDFrame.describe of    주문번호 고객명     메뉴  수량    가격 회원여부         방문일  리뷰점수
0   101  민지  아메리카노   2  4500   회원  2026-09-01   5.0
1   102  준호   카페라떼   1  5000  비회원  2026-09-01   NaN
2   103  서연  딸기스무디   1  5500   회원  2026-09-02   4.0
3   104  도윤  아메리카노   3  4500   회원  2026-09-02   5.0
4   105  하은   녹차라떼   1  5200  비회원  2026-09-03   3.0
5   106  지훈   카페라떼   2  5000   회원  2026-09-03   NaN
6   107  예린  초코케이크   1  6000   회원  2026-09-04   5.0
7   108  현우  아메리카노   1  4500  비회원  2026-09-04   4.0>

In [ ]:
df.columns

Index(['주문번호', '고객명', '메뉴', '수량', '가격', '회원여부', '방문일', '리뷰점수'], dtype='str')