### 조회와 선택
- 원하는 열과 행을 꺼내는 방법 익히기
- 조건 걸어서 해보기
- 특정 열과 행을 선택해서 처리해야 하는 경우가 거의 대부분이다

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/3-1_students.csv")
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

### 1. 열 하나 선택
- df['열이름']

In [4]:
df['이름']

0    김민준
1    이서연
2    박도윤
3    최지우
4    정하준
5    이서연
Name: 이름, dtype: str

In [5]:
df['국어']

0    90.0
1    85.0
2     NaN
3    70.0
4    88.0
5    85.0
Name: 국어, dtype: float64

In [7]:
df.head

<bound method NDFrame.head of     이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78>

In [8]:
df.info

<bound method DataFrame.info of     이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78>

In [9]:
df.shape

(6, 6)

In [10]:
df.describe

<bound method NDFrame.describe of     이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78>

### 2. 여러 열 선택
- df[['열1']]

In [11]:
df[['국어','이름']]

     국어   이름
0  90.0  김민준
1  85.0  이서연
2   NaN  박도윤
3  70.0  최지우
4  88.0  정하준
5  85.0  이서연

In [13]:
df.head()

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석

In [15]:
df[['반','이름','수학']]

   반   이름   수학
0  A  김민준  100
1  B  이서연   78
2  A  박도윤   88
3  B  최지우   65
4  A  정하준   결석
5  B  이서연   78

### 3. 행 선택 - loc(이를표로 찾기)
- loc 행의 인덱스 라벨명으로 행을 꺼냅니다.
- 지금 위의 데이터에서는 라벨명이 0,1,2,3

In [16]:
df.loc[0]

이름     김민준
반        A
성별       남
국어    90.0
영어    80.0
수학     100
Name: 0, dtype: object

In [17]:
df.loc[0:2]

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88

In [20]:
df.index = ["A","B","C","D","E","F"]
df

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
C  박도윤  A  남   NaN  75.0   88
D  최지우  B  여  70.0   NaN   65
E  정하준  A  남  88.0  95.0   결석
F  이서연  B  여  85.0  92.0   78

In [21]:
df.loc["A":"D"]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
C  박도윤  A  남   NaN  75.0   88
D  최지우  B  여  70.0   NaN   65

### 4. 행 선택 - iloc (순서번호로 찾기)
- 몇 번째인지 순서로 꺼낸다.
- 파이썬 슬라이싱

In [22]:
df.iloc[0]

이름     김민준
반        A
성별       남
국어    90.0
영어    80.0
수학     100
Name: A, dtype: object

In [23]:
df.iloc[0:4]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
C  박도윤  A  남   NaN  75.0   88
D  최지우  B  여  70.0   NaN   65

In [54]:
df.iloc[3:5, 2:4 ]

  성별    국어
D  여  70.0
E  남  88.0

In [24]:
df.head()

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
C  박도윤  A  남   NaN  75.0   88
D  최지우  B  여  70.0   NaN   65
E  정하준  A  남  88.0  95.0   결석

In [27]:
df.loc["B":"D"][["반","성별","국어"]]

   반 성별    국어
B  B  여  85.0
C  A  남   NaN
D  B  여  70.0

### 5. 조건으로 데이터 가져오기

In [28]:
df.head()

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
C  박도윤  A  남   NaN  75.0   88
D  최지우  B  여  70.0   NaN   65
E  정하준  A  남  88.0  95.0   결석

In [30]:
df[df['성별'] == '남']

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
C  박도윤  A  남   NaN  75.0   88
E  정하준  A  남  88.0  95.0   결석

In [31]:
df[df['국어'] > 85]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
E  정하준  A  남  88.0  95.0   결석

In [33]:
df[df['영어'] >= 80]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
E  정하준  A  남  88.0  95.0   결석
F  이서연  B  여  85.0  92.0   78

In [ ]:
df[df['수학'] >= 80] # 결석 때문에 안된다 -> 전처리가 필요

TypeError: '>=' not supported between instances of 'str' and 'int'

### 6. 여러 조건 - &(그리고),|(또는) 
- 조건이 여러개면 &, | 로 적절하게
- 각 조건은 소괄호로 감싸야합니다.

In [38]:
# A 반이면서 국어가 85점이상 학생
df[ (df["반"] == 'A') & (df['국어'] >= 85 ) ]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
E  정하준  A  남  88.0  95.0   결석

In [39]:
df.head

<bound method NDFrame.head of     이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
C  박도윤  A  남   NaN  75.0   88
D  최지우  B  여  70.0   NaN   65
E  정하준  A  남  88.0  95.0   결석
F  이서연  B  여  85.0  92.0   78>

In [44]:
df[(df['성별'] == '여') & ( df['영어'] > 90)]

    이름  반 성별    국어    영어  수학
B  이서연  B  여  85.0  92.0  78
F  이서연  B  여  85.0  92.0  78

In [51]:
df[(df['성별'] == '여') | ( df['국어'] > 80)]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
D  최지우  B  여  70.0   NaN   65
E  정하준  A  남  88.0  95.0   결석
F  이서연  B  여  85.0  92.0   78

In [52]:
df.head()

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
C  박도윤  A  남   NaN  75.0   88
D  최지우  B  여  70.0   NaN   65
E  정하준  A  남  88.0  95.0   결석

In [53]:
# 영어가 90점 이상이거나, 국어가 86점 이상인 사람은?
df[ (df["국어"] >= 86) | ( df["영어"] >= 90 )  ]

    이름  반 성별    국어    영어   수학
A  김민준  A  남  90.0  80.0  100
B  이서연  B  여  85.0  92.0   78
E  정하준  A  남  88.0  95.0   결석
F  이서연  B  여  85.0  92.0   78