### 데이터 정제 및 전처리
- 중요한 이유
    - 현실 데이터는 빈칸, 중복, 잘못된 형식도 정말 많습니다.
    - 지저분한 데이터는 그대로 분석하면 안됩니다.
    - 정제하는게 가장 핵심

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/3-1_students.csv")
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

In [5]:
df.isna()

      이름      반     성별     국어     영어     수학
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False  False   True  False  False
3  False  False  False  False   True  False
4  False  False  False  False  False  False
5  False  False  False  False  False  False

In [7]:
df.isna().sum()

이름    0
반     0
성별    0
국어    1
영어    1
수학    0
dtype: int64

In [9]:
df.dropna()

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

In [ ]:
df   # 최신본으로 유지
df_copy = df.copy # 적절하게 전처리 된 중간 데이터 프레임을 원본으로 보관하기

In [16]:
df = df.dropna()
df_copy = df.copy()

In [19]:
df_copy

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

In [21]:
df = pd.read_csv("../data/3-1_students.csv")
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남   NaN  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

In [25]:
# 결측치를 평균으로 채우기
korean_score = df['국어'].mean()
df['국어'].fillna(korean_score)

0    90.0
1    85.0
2    83.6
3    70.0
4    88.0
5    85.0
Name: 국어, dtype: float64

In [26]:
df['국어'] = df['국어'].fillna(korean_score)
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남  83.6  75.0   88
3  최지우  B  여  70.0   NaN   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

In [28]:
df['영어'] = df['영어'].fillna(df['영어'].mean())
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남  83.6  75.0   88
3  최지우  B  여  70.0  86.8   65
4  정하준  A  남  88.0  95.0   결석
5  이서연  B  여  85.0  92.0   78

### 4. 중복 데이터 처리
- duplicated()

In [29]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [30]:
df.drop_duplicates()

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남  83.6  75.0   88
3  최지우  B  여  70.0  86.8   65
4  정하준  A  남  88.0  95.0   결석

In [32]:
df = df.drop_duplicates()
df

    이름  반 성별    국어    영어   수학
0  김민준  A  남  90.0  80.0  100
1  이서연  B  여  85.0  92.0   78
2  박도윤  A  남  83.6  75.0   88
3  최지우  B  여  70.0  86.8   65
4  정하준  A  남  88.0  95.0   결석

### 6. 타입을 고치기
- 숫자여야 할 부분이 아닌 값들은 -> NaN 으로 바꾸기
- pd.to_numeric()

In [33]:
pd.to_numeric( df['수학'],errors="coerce")

0    100.0
1     78.0
2     88.0
3     65.0
4      NaN
Name: 수학, dtype: float64

In [35]:
df['수학'] = pd.to_numeric( df['수학'],errors="coerce")
df

    이름  반 성별    국어    영어     수학
0  김민준  A  남  90.0  80.0  100.0
1  이서연  B  여  85.0  92.0   78.0
2  박도윤  A  남  83.6  75.0   88.0
3  최지우  B  여  70.0  86.8   65.0
4  정하준  A  남  88.0  95.0    NaN

In [36]:
df['수학'] = df['수학'].fillna(df['영어'].mean())
df

    이름  반 성별    국어    영어      수학
0  김민준  A  남  90.0  80.0  100.00
1  이서연  B  여  85.0  92.0   78.00
2  박도윤  A  남  83.6  75.0   88.00
3  최지우  B  여  70.0  86.8   65.00
4  정하준  A  남  88.0  95.0   85.76

### 7. 이상치 확인하기
- 만약에 사실 위에서 수학은 90점이 사실 만점이었다고 생각해봅시다. -> 10점은 수행이어서 사실 90점이상은 잘못 적힌것이다.

In [37]:
df[df['수학'] > 90]

    이름  반 성별    국어    영어     수학
0  김민준  A  남  90.0  80.0  100.0

In [38]:
# 이상 데이터 개수 확인하가
print(len(df[df['수학'] > 90 ]))

1