### 도시 공원 데이터
- 우리 도시에 공원이 충분할까?
- 지역마다 어떤 차이가 있을까?>
- 간단한 의문부터 시작
- 이런 것들이 시민의 삶의 질, 복지, 등등, 사업 등과 연결이 가능하기 때문에

- **새롭게 알게된 사실 -> 인사이트**

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/3-4_city_park.csv")
df.head()

,관리번호,공원명,공원구분,소재지도로명주소,소재지지번주소,위도,경도,공원면적,공원보유시설(운동시설),공원보유시설(유희시설),공원보유시설(편익시설),공원보유시설(교양시설),공원보유시설(기타시설),지정고시일,관리기관명,전화번호,데이터기준일자
0,26200-00001,태종대유원지,기타,부산광역시 영도구 전망로 24,부산광역시 영도구 동삼동 산 19-2,35.059695,129.079806,1713763.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-04
1,26110-00001,용두산공원,근린공원,부산광역시 중구 용두산길 37-55,부산광역시 중구 광복동 2가 1-2,35.100209,129.032278,70812.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-04
2,29200-00028,월전공원,근린공원,NaN,광주광역시 광산구 장록동 751-1,35.132211,126.768588,40038.5,NaN,NaN,NaN,NaN,NaN,1991-06-25,광주광역시 광산구,062-960-6839,2026-06-29
3,29140-00054,극락어린이공원,어린이공원,NaN,광주광역시 서구 유촌동 857,35.165298,126.858437,1643.3,NaN,NaN,NaN,NaN,NaN,1996-07-11,광주광역시 서구청,062-360-7697,2026-06-29
4,29140-00053,서광어린이공원,어린이공원,NaN,광주광역시 서구 쌍촌동 1358,35.157193,126.864497,3067.2,NaN,NaN,NaN,NaN,NaN,1996-07-11,광주광역시 서구청,062-360-7697,2026-06-29

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18499 entries, 0 to 18498
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   관리번호          18499 non-null  str
 1   공원명           18499 non-null  str
 2   공원구분          18499 non-null  str
 3   소재지도로명주소      3131 non-null   str
 4   소재지지번주소       18310 non-null  str
 5   위도            18499 non-null  float64
 6   경도            18499 non-null  float64
 7   공원면적          18499 non-null  float64
 8   공원보유시설(운동시설)  5370 non-null   str
 9   공원보유시설(유희시설)  6252 non-null   str
 10  공원보유시설(편익시설)  5110 non-null   str
 11  공원보유시설(교양시설)  548 non-null    str
 12  공원보유시설(기타시설)  2747 non-null   str
 13  지정고시일         15230 non-null  str
 14  관리기관명         17507 non-null  str
 15  전화번호          17526 non-null  str
 16  데이터기준일자       18499 non-null  str
dtypes: float64(3), str(14)
memory usage: 2.4 MB

### 데이터를 그래도 쓰지않고 조건을 정해서 처리
- 공원면적을 통계확인

In [7]:
df.describe()

                 위도            경도          공원면적
count  18499.000000  18499.000000  1.849900e+04
mean      36.502789    127.469601  3.033110e+04
std        1.029747      0.847369  2.133286e+05
min       33.218571    125.433012  0.000000e+00
25%       35.558629    126.864257  1.503000e+03
50%       36.785392    127.104036  2.281800e+03
75%       37.433572    128.082836  1.025750e+04
max       38.491242    137.202661  1.486486e+07

In [2]:
df['공원면적'].mean()

NameError: name 'df' is not defined

In [6]:
df.columns

Index(['관리번호', '공원명', '공원구분', '소재지도로명주소', '소재지지번주소', '위도', '경도', '공원면적',
       '공원보유시설(운동시설)', '공원보유시설(유희시설)', '공원보유시설(편익시설)', '공원보유시설(교양시설)',
       '공원보유시설(기타시설)', '지정고시일', '관리기관명', '전화번호', '데이터기준일자'],
      dtype='str')

In [21]:
columns = ["공원명","공원구분","공원면적","관리기관명"]

clean_df = df[columns]
clean_df

           공원명   공원구분       공원면적      관리기관명
0       태종대유원지     기타  1713763.0        NaN
1        용두산공원   근린공원    70812.0        NaN
2         월전공원   근린공원    40038.5  광주광역시 광산구
3      극락어린이공원  어린이공원     1643.3  광주광역시 서구청
4      서광어린이공원  어린이공원     3067.2  광주광역시 서구청
...        ...    ...        ...        ...
18494       율곡  어린이공원     4216.0  광주광역시 동구청
18495       천변   수변공원   108420.0  광주광역시 동구청
18496      계림8   문화공원     5999.0  광주광역시 동구청
18497       학동   역사공원     2049.3  광주광역시 동구청
18498      내남3    소공원     1624.0  광주광역시 동구청

[18499 rows x 4 columns]

In [11]:
clean_df['큰공원여부'] = clean_df["공원면적"] >= 50000
clean_df.head()

       공원명   공원구분       공원면적  큰공원여부
0   태종대유원지     기타  1713763.0   True
1    용두산공원   근린공원    70812.0   True
2     월전공원   근린공원    40038.5  False
3  극락어린이공원  어린이공원     1643.3  False
4  서광어린이공원  어린이공원     3067.2  False

### 2. 면적순으로 한번 보고 싶다 -> 정렬 개념
- 큰값부터 정렬
- 작은값부터 정렬

In [13]:
clean_df.sort_values("공원면적")

                     공원명  공원구분        공원면적  큰공원여부
3627        1호 소공원(지제지구)   소공원         0.0  False
3625    1호 소공원(포승지구 BIX)   소공원         0.0  False
3623   1호 수변공원(포승지구 BIX)  수변공원         0.0  False
3632   12호 근린공원(고덕국제화지구)  근린공원         0.0  False
3631   1호 근린공원(포승지구 BIX)  근린공원         0.0  False
...                  ...   ...         ...    ...
8868             모악산도립공원  근린공원   5608490.0   True
2745            수락산<시공원>    기타   6691885.3   True
14936            불광산근린공원  근린공원   7404000.0   True
6304               옥녀봉공원  근린공원   9320660.0   True
4697      랜드마크시티 1호 체육공원  체육공원  14864860.0   True

[18499 rows x 4 columns]

In [14]:
clean_df.sort_values("공원면적", ascending=False)

                  공원명  공원구분        공원면적  큰공원여부
4697   랜드마크시티 1호 체육공원  체육공원  14864860.0   True
6304            옥녀봉공원  근린공원   9320660.0   True
14936         불광산근린공원  근린공원   7404000.0   True
2745         수락산<시공원>    기타   6691885.3   True
8868          모악산도립공원  근린공원   5608490.0   True
...               ...   ...         ...    ...
3626    1호 소공원(진위3지구)   소공원         0.0  False
3628     1호 소공원(장당지구)   소공원         0.0  False
18067           대구대공원  근린공원         0.0  False
3429          율리 근린공원  근린공원         0.0  False
3772          봉남 근린공원  근린공원         0.0  False

[18499 rows x 4 columns]

### 3. 어떤 특정 그룹별로 한번 집계를 해보고 싶다(통계계산)
- groupby
- 공원 종류별로 묶어서, 개수가 몇개인지, 합계는 몇인지, 평균 면적은 얼마인지
- 어떤 종류의 공원이 많은지

In [16]:
# 공원면적이 0인 값, 혹은 얼마 이하인 값들은 제거해야 할 것 같다. -> 아직 처리는 안함
clean_df.groupby("공원구분")["공원면적"].count()

공원구분
가로공원         3
근린공원      4112
기타         539
기타공원        29
도시농업공원       7
마을마당         1
묘지공원        39
문화공원       483
소공원       3105
수변공원       405
어린이공원     9301
역사공원       204
주제공원         2
체육공원       269
Name: 공원면적, dtype: int64

In [18]:
summary = clean_df.groupby("공원구분")["공원면적"].agg(["count","sum","mean","median"])
summary

        count           sum           mean     median
공원구분
가로공원        3  1.197100e+04    3990.333333    3272.00
근린공원     4112  3.898640e+08   94811.291314   24909.50
기타        539  2.889889e+07   53615.742356    1117.00
기타공원       29  2.142740e+04     738.875862     335.90
도시농업공원      7  3.158591e+06  451227.271429   49805.90
마을마당        1  5.849000e+02     584.900000     584.90
묘지공원       39  1.821648e+07  467089.287179  214640.40
문화공원      483  2.225936e+07   46085.635197    7721.00
소공원      3105  8.511675e+06    2741.280167    1137.00
수변공원      405  1.307368e+07   32280.692346   11688.20
어린이공원    9301  3.000545e+07    3226.045285    1785.00
역사공원      204  1.199243e+07   58786.443235   15933.00
주제공원        2  6.257890e+04   31289.450000   31289.45
체육공원      269  3.501785e+07  130177.881784   25562.00

In [19]:
summary.sort_values("count",ascending=False)

        count           sum           mean     median
공원구분
어린이공원    9301  3.000545e+07    3226.045285    1785.00
근린공원     4112  3.898640e+08   94811.291314   24909.50
소공원      3105  8.511675e+06    2741.280167    1137.00
기타        539  2.889889e+07   53615.742356    1117.00
문화공원      483  2.225936e+07   46085.635197    7721.00
수변공원      405  1.307368e+07   32280.692346   11688.20
체육공원      269  3.501785e+07  130177.881784   25562.00
역사공원      204  1.199243e+07   58786.443235   15933.00
묘지공원       39  1.821648e+07  467089.287179  214640.40
기타공원       29  2.142740e+04     738.875862     335.90
도시농업공원      7  3.158591e+06  451227.271429   49805.90
가로공원        3  1.197100e+04    3990.333333    3272.00
주제공원        2  6.257890e+04   31289.450000   31289.45
마을마당        1  5.849000e+02     584.900000     584.90

####  인사이트
- 어린이공원, 소공원은 개수가 많지만 크기가 작다.
- 근린공원은 평균 면적이 크다.  전체 공원면적이 크다.
- 개수 1 위는 어린이공원이지만, 전체면적으로 보면 근린공원이 주된 공원이라고 할수도 있다.
- 근린공원위주로 가야 한다.

#### 4. 교차표 만들기 - pivot_table
- 어떤 두 컬럼(범주) 를 가로,세로로 교차시켜서 요약하는 
- 관리기관 * 공원구분의 평균 면적을 같이 보려고 할 때

In [24]:
table_df = clean_df.pivot_table(index="관리기관명", 
                                columns="공원구분", 
                                values="공원명",
                                aggfunc="count",
                                fill_value=0
                                )
table_df

공원구분,가로공원,근린공원,기타,기타공원,도시농업공원,마을마당,묘지공원,문화공원,소공원,수변공원,어린이공원,역사공원,주제공원,체육공원
관리기관명,,,,,,,,,,,,,,
(사)광주광역시교통문화연수원,0,0,0,0,0,0,0,0,0,0,1,0,0,0
(주)한국수력원자력,0,1,0,0,0,0,0,0,0,0,0,0,0,0
강원도 철원군청,0,4,0,0,0,0,0,2,1,1,13,1,0,0
강원도 평창군청,0,5,0,0,0,0,0,0,10,0,8,0,0,1
강원도 횡성군청 도시행정과,0,6,0,0,0,0,0,0,7,0,18,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
충청북도 증평군청 휴양랜드사업소,0,1,0,0,0,0,0,0,0,0,0,0,0,0
충청북도 진천군청,0,12,1,0,0,0,0,0,7,2,11,1,0,2
충청북도 청주시 공원산림본부 공원관리과,0,118,8,0,0,0,1,2,71,20,207,4,0,2
충청북도 충주시청,0,36,0,0,0,0,0,0,29,0,54,0,0,0
한수원㈜ 한울원자력본부,0,0,0,0,0,0,0,0,0,0,2,0,0,0

### 5. pivot_table <-> melt
- melt 는 그 반대역할

In [27]:
df.head()

,관리번호,공원명,공원구분,소재지도로명주소,소재지지번주소,위도,경도,공원면적,공원보유시설(운동시설),공원보유시설(유희시설),공원보유시설(편익시설),공원보유시설(교양시설),공원보유시설(기타시설),지정고시일,관리기관명,전화번호,데이터기준일자
0,26200-00001,태종대유원지,기타,부산광역시 영도구 전망로 24,부산광역시 영도구 동삼동 산 19-2,35.059695,129.079806,1713763.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-04
1,26110-00001,용두산공원,근린공원,부산광역시 중구 용두산길 37-55,부산광역시 중구 광복동 2가 1-2,35.100209,129.032278,70812.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-04
2,29200-00028,월전공원,근린공원,NaN,광주광역시 광산구 장록동 751-1,35.132211,126.768588,40038.5,NaN,NaN,NaN,NaN,NaN,1991-06-25,광주광역시 광산구,062-960-6839,2026-06-29
3,29140-00054,극락어린이공원,어린이공원,NaN,광주광역시 서구 유촌동 857,35.165298,126.858437,1643.3,NaN,NaN,NaN,NaN,NaN,1996-07-11,광주광역시 서구청,062-360-7697,2026-06-29
4,29140-00053,서광어린이공원,어린이공원,NaN,광주광역시 서구 쌍촌동 1358,35.157193,126.864497,3067.2,NaN,NaN,NaN,NaN,NaN,1996-07-11,광주광역시 서구청,062-360-7697,2026-06-29

In [28]:
df.columns

Index(['관리번호', '공원명', '공원구분', '소재지도로명주소', '소재지지번주소', '위도', '경도', '공원면적',
       '공원보유시설(운동시설)', '공원보유시설(유희시설)', '공원보유시설(편익시설)', '공원보유시설(교양시설)',
       '공원보유시설(기타시설)', '지정고시일', '관리기관명', '전화번호', '데이터기준일자'],
      dtype='str')

In [30]:
df.head()

,관리번호,공원명,공원구분,소재지도로명주소,소재지지번주소,위도,경도,공원면적,공원보유시설(운동시설),공원보유시설(유희시설),공원보유시설(편익시설),공원보유시설(교양시설),공원보유시설(기타시설),지정고시일,관리기관명,전화번호,데이터기준일자
0,26200-00001,태종대유원지,기타,부산광역시 영도구 전망로 24,부산광역시 영도구 동삼동 산 19-2,35.059695,129.079806,1713763.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-04
1,26110-00001,용두산공원,근린공원,부산광역시 중구 용두산길 37-55,부산광역시 중구 광복동 2가 1-2,35.100209,129.032278,70812.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-04
2,29200-00028,월전공원,근린공원,NaN,광주광역시 광산구 장록동 751-1,35.132211,126.768588,40038.5,NaN,NaN,NaN,NaN,NaN,1991-06-25,광주광역시 광산구,062-960-6839,2026-06-29
3,29140-00054,극락어린이공원,어린이공원,NaN,광주광역시 서구 유촌동 857,35.165298,126.858437,1643.3,NaN,NaN,NaN,NaN,NaN,1996-07-11,광주광역시 서구청,062-360-7697,2026-06-29
4,29140-00053,서광어린이공원,어린이공원,NaN,광주광역시 서구 쌍촌동 1358,35.157193,126.864497,3067.2,NaN,NaN,NaN,NaN,NaN,1996-07-11,광주광역시 서구청,062-360-7697,2026-06-29

In [31]:
clean_df

           공원명   공원구분       공원면적      관리기관명
0       태종대유원지     기타  1713763.0        NaN
1        용두산공원   근린공원    70812.0        NaN
2         월전공원   근린공원    40038.5  광주광역시 광산구
3      극락어린이공원  어린이공원     1643.3  광주광역시 서구청
4      서광어린이공원  어린이공원     3067.2  광주광역시 서구청
...        ...    ...        ...        ...
18494       율곡  어린이공원     4216.0  광주광역시 동구청
18495       천변   수변공원   108420.0  광주광역시 동구청
18496      계림8   문화공원     5999.0  광주광역시 동구청
18497       학동   역사공원     2049.3  광주광역시 동구청
18498      내남3    소공원     1624.0  광주광역시 동구청

[18499 rows x 4 columns]

In [32]:
# apply 기능을 활용
clean_df.head()

       공원명   공원구분       공원면적      관리기관명
0   태종대유원지     기타  1713763.0        NaN
1    용두산공원   근린공원    70812.0        NaN
2     월전공원   근린공원    40038.5  광주광역시 광산구
3  극락어린이공원  어린이공원     1643.3  광주광역시 서구청
4  서광어린이공원  어린이공원     3067.2  광주광역시 서구청

In [34]:
# 세분화 해본다면
# 50000이상 -> 큰공원
# 30000 ~ 50000 -> 중간공원
# 30000이하 -> 작은 공원

clean_df['규모'] = clean_df['공원면적'].apply(lambda x: "큰공원" if x >=50000 else ("중간공원" if x>=30000 else "작은공원"))
clean_df.head()

       공원명   공원구분       공원면적      관리기관명    규모
0   태종대유원지     기타  1713763.0        NaN   큰공원
1    용두산공원   근린공원    70812.0        NaN   큰공원
2     월전공원   근린공원    40038.5  광주광역시 광산구  중간공원
3  극락어린이공원  어린이공원     1643.3  광주광역시 서구청  작은공원
4  서광어린이공원  어린이공원     3067.2  광주광역시 서구청  작은공원

In [ ]:
def cleaned_fnc(x):
    if x >= 50000:
        return "큰공원"