### 1. 데이터 찾기 - 의도가 중요 : 궁금한거, 알아보고 싶은 것 생각 -> 잘모르겠다 코덱스  -- 지역별 영화관 개수 찾기
### 2. 데이터 정제 및 전처리
### 3. 병합 및 집계
### 4. 인사이트 정리

제출하기 - 구글드라이브에 잘되던 안되던 제출하기

In [4]:
import pandas

# 1. 원본 CSV 파일을 CP949 인코딩으로 읽습니다.
df = pandas.read_csv("../data/3-6_movie_theater.csv",encoding="cp949")

#df = pd.read_csv("../data/3-4_city_park.csv")

# 2. UTF-8 형식의 새 파일로 저장합니다.
# utf-8-sig: 엑셀에서도 한글이 비교적 잘 보이는 UTF-8 방식입니다.
df.to_csv(
      "../data/3-6_movie_theater_utf8.csv",
      encoding="utf-8-sig",
      index=False
)

print("저장 완료: ../data/3-6_movie_theater_utf8.csv")
# AI 도움으로 읽기 부분 수정 요청 해서 생성된 코드 입니다.

저장 완료: ../data/3-6_movie_theater_utf8.csv

In [ ]:
df = pandas.read_csv("../data/3-6_movie_theater_utf8.csv",encoding="utf8")  # 판다스 파일 읽기
df.head()

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태명,폐업일자,휴업시작일자,휴업종료일자,소재지우편번호,도로명우편번호,...,주변환경명,지번주소,지상층수,지역구분명,지하층수,청소년실수,총층수,최초등록시점,통로너비,최종수정시점
0,3000000,CDFF4220002010000001,2010-04-15,NaN,폐업,2022-02-17,NaN,NaN,NaN,NaN,...,NaN,서울특별시 종로구 신문로2가 1-153 2층,1.0,NaN,3.0,NaN,4.0,2010-04-15,NaN,2022-03-25 13:09:35
1,3000000,CDFF4220002011000001,2011-03-23,NaN,폐업,2012-05-29,NaN,NaN,NaN,NaN,...,NaN,서울특별시 종로구 신문로2가 1-153 가든플레이스 2층,3.0,NaN,1.0,NaN,4.0,2011-03-23,NaN,2012-06-08 14:44:56
2,3000000,CDFF4220002011000002,2011-05-23,NaN,폐업,2013-08-09,NaN,NaN,NaN,NaN,...,NaN,서울특별시 종로구 명륜3가 109-4 지하1층,3.0,NaN,1.0,NaN,4.0,2011-05-23,NaN,2013-08-09 16:53:32
3,3000000,CDFF4220002003000010,2003-02-12,NaN,영업/정상,NaN,NaN,NaN,NaN,4051.0,...,NaN,서울특별시 마포구 동교동 166-14 동교동 스타피카소,NaN,NaN,NaN,NaN,NaN,2003-02-12,NaN,2022-02-21 11:00:52
4,3000000,CDFF4220002003000013,2003-02-12,NaN,영업/정상,NaN,NaN,NaN,NaN,NaN,...,NaN,서울특별시 종로구 낙원동 284-6,NaN,NaN,NaN,NaN,NaN,2003-02-12,NaN,2020-03-23 14:02:25

In [5]:
df.columns  # 컬럼 정보 보기

Index(['개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자', '영업상태명', '폐업일자', '휴업시작일자',
       '휴업종료일자', '소재지우편번호', '도로명우편번호', '사업장명', '데이터갱신구분', '건물용도명', '공연장형태구분명',
       '노래방실수', '데이터갱신시점', '도로명주소', '문화사업자구분명', '문화체육업종명', '상세영업상태명',
       '상세영업상태코드', '시설면적', '영업상태코드', '전화번호', '제작취급품목내용', '좌표정보(X)', '좌표정보(Y)',
       '주변환경명', '지번주소', '지상층수', '지역구분명', '지하층수', '청소년실수', '총층수', '최초등록시점',
       '통로너비', '최종수정시점'],
      dtype='str')

In [ ]:
df.info()   # 컬럼명 데이터 타입 새로로 보기

<class 'pandas.DataFrame'>
RangeIndex: 5233 entries, 0 to 5232
Data columns (total 37 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  5233 non-null   int64
 1   관리번호      5233 non-null   str
 2   인허가일자     5233 non-null   str
 3   인허가취소일자   0 non-null      float64
 4   영업상태명     5233 non-null   str
 5   폐업일자      1532 non-null   str
 6   휴업시작일자    73 non-null     str
 7   휴업종료일자    66 non-null     str
 8   소재지우편번호   1107 non-null   str
 9   도로명우편번호   3528 non-null   float64
 10  사업장명      5233 non-null   str
 11  데이터갱신구분   5233 non-null   str
 12  건물용도명     2730 non-null   str
 13  공연장형태구분명  5173 non-null   str
 14  노래방실수     0 non-null      float64
 15  데이터갱신시점   5233 non-null   str
 16  도로명주소     4871 non-null   str
 17  문화사업자구분명  2834 non-null   str
 18  문화체육업종명   5233 non-null   str
 19  상세영업상태명   5219 non-null   str
 20  상세영업상태코드  5233 non-null   str
 21  시설면적      91 non-null     float64
 22  영업상태코드    5233 non-null   int64
 23  전화번호      2799 non-null   float64
 24  제작취급품목내용  0 non-null      float64
 25  좌표정보(X)   4924 non-null   float64
 26  좌표정보(Y)   4924 non-null   float64
 27  주변환경명     1843 non-null   str
 28  지번주소      5233 non-null   str
 29  지상층수      3936 non-null   float64
 30  지역구분명     2290 non-null   str
 31  지하층수      3368 non-null   float64
 32  청소년실수     0 non-null      float64
 33  총층수       3059 non-null   float64
 34  최초등록시점    5233 non-null   str
 35  통로너비      822 non-null    float64
 36  최종수정시점    5233 non-null   str
dtypes: float64(13), int64(2), str(22)
memory usage: 1.5 MB

In [6]:
# info()에서 표시할 최대 컬럼 수를 늘리기
pandas.set_option("display.max_info_columns", 200)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5233 entries, 0 to 5232
Data columns (total 37 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  5233 non-null   int64
 1   관리번호      5233 non-null   str
 2   인허가일자     5233 non-null   str
 3   인허가취소일자   0 non-null      float64
 4   영업상태명     5233 non-null   str
 5   폐업일자      1532 non-null   str
 6   휴업시작일자    73 non-null     str
 7   휴업종료일자    66 non-null     str
 8   소재지우편번호   1107 non-null   str
 9   도로명우편번호   3528 non-null   float64
 10  사업장명      5233 non-null   str
 11  데이터갱신구분   5233 non-null   str
 12  건물용도명     2730 non-null   str
 13  공연장형태구분명  5173 non-null   str
 14  노래방실수     0 non-null      float64
 15  데이터갱신시점   5233 non-null   str
 16  도로명주소     4871 non-null   str
 17  문화사업자구분명  2834 non-null   str
 18  문화체육업종명   5233 non-null   str
 19  상세영업상태명   5219 non-null   str
 20  상세영업상태코드  5233 non-null   str
 21  시설면적      91 non-null     float64
 22  영업상태코드    5233 non-null   int64
 23  전화번호      2799 non-null   float64
 24  제작취급품목내용  0 non-null      float64
 25  좌표정보(X)   4924 non-null   float64
 26  좌표정보(Y)   4924 non-null   float64
 27  주변환경명     1843 non-null   str
 28  지번주소      5233 non-null   str
 29  지상층수      3936 non-null   float64
 30  지역구분명     2290 non-null   str
 31  지하층수      3368 non-null   float64
 32  청소년실수     0 non-null      float64
 33  총층수       3059 non-null   float64
 34  최초등록시점    5233 non-null   str
 35  통로너비      822 non-null    float64
 36  최종수정시점    5233 non-null   str
dtypes: float64(13), int64(2), str(22)
memory usage: 1.5 MB

In [14]:
# 0번부터 20번까지 출력
for i, col in enumerate(df.columns[:20]):
    sample = df[col].dropna().iloc[0] if not df[col].dropna().empty else "None"
    print(f"[{i:2d}] {col} ({df[col].dtype}) ➔ 예시: {sample}")

print("-" * 50)

[ 0] 개방자치단체코드 (int64) ➔ 예시: 3000000
[ 1] 관리번호 (str) ➔ 예시: CDFF4220002010000001
[ 2] 인허가일자 (str) ➔ 예시: 2010-04-15
[ 3] 인허가취소일자 (float64) ➔ 예시: None
[ 4] 영업상태명 (str) ➔ 예시: 폐업
[ 5] 폐업일자 (str) ➔ 예시: 2022-02-17
[ 6] 휴업시작일자 (str) ➔ 예시: 2025-03-15
[ 7] 휴업종료일자 (str) ➔ 예시: 2027-01-31
[ 8] 소재지우편번호 (str) ➔ 예시: 110-833
[ 9] 도로명우편번호 (float64) ➔ 예시: 4051.0
[10] 사업장명 (str) ➔ 예시: 독립영화전용관 시네마루
[11] 데이터갱신구분 (str) ➔ 예시: I
[12] 건물용도명 (str) ➔ 예시: 문화시설
[13] 공연장형태구분명 (str) ➔ 예시: 영화관
[14] 노래방실수 (float64) ➔ 예시: None
[15] 데이터갱신시점 (str) ➔ 예시: 2026-05-10 22:41:08
[16] 도로명주소 (str) ➔ 예시: 서울특별시 종로구 경희궁1길 1 (신문로2가,2층)
[17] 문화사업자구분명 (str) ➔ 예시: 영화상영관
[18] 문화체육업종명 (str) ➔ 예시: 영화상영관
[19] 상세영업상태명 (str) ➔ 예시: 폐업
--------------------------------------------------

In [15]:
# 20번부터 끝까지 출력
for i, col in enumerate(df.columns[20:], start=20):
    sample = df[col].dropna().iloc[0] if not df[col].dropna().empty else "None"
    print(f"[{i:2d}] {col} ({df[col].dtype}) ➔ 예시: {sample}")

[20] 상세영업상태코드 (str) ➔ 예시: 03
[21] 시설면적 (float64) ➔ 예시: 356.4
[22] 영업상태코드 (int64) ➔ 예시: 3
[23] 전화번호 (float64) ➔ 예시: 32103358.0
[24] 제작취급품목내용 (float64) ➔ 예시: None
[25] 좌표정보(X) (float64) ➔ 예시: 197428.923002637
[26] 좌표정보(Y) (float64) ➔ 예시: 452041.177877529
[27] 주변환경명 (str) ➔ 예시: 기타
[28] 지번주소 (str) ➔ 예시: 서울특별시 종로구 신문로2가 1-153 2층
[29] 지상층수 (float64) ➔ 예시: 1.0
[30] 지역구분명 (str) ➔ 예시: 근린상업지역
[31] 지하층수 (float64) ➔ 예시: 3.0
[32] 청소년실수 (float64) ➔ 예시: None
[33] 총층수 (float64) ➔ 예시: 4.0
[34] 최초등록시점 (str) ➔ 예시: 2010-04-15
[35] 통로너비 (float64) ➔ 예시: 1.0
[36] 최종수정시점 (str) ➔ 예시: 2022-03-25 13:09:35

In [18]:
# 최대 출력 컬럼 수 제한 해제 (가장 중요)
pandas.set_option("display.max_columns", None)

# 컬럼 내부 글자 잘림 방지 (선택)
pandas.set_option("display.max_colwidth", None)

df.head()

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태명,폐업일자,휴업시작일자,휴업종료일자,소재지우편번호,도로명우편번호,사업장명,데이터갱신구분,건물용도명,공연장형태구분명,노래방실수,데이터갱신시점,도로명주소,문화사업자구분명,문화체육업종명,상세영업상태명,상세영업상태코드,시설면적,영업상태코드,전화번호,제작취급품목내용,좌표정보(X),좌표정보(Y),주변환경명,지번주소,지상층수,지역구분명,지하층수,청소년실수,총층수,최초등록시점,통로너비,최종수정시점
0,3000000,CDFF4220002010000001,2010-04-15,NaN,폐업,2022-02-17,NaN,NaN,NaN,NaN,독립영화전용관 시네마루,I,NaN,영화관,NaN,2026-05-10 22:41:08,"서울특별시 종로구 경희궁1길 1 (신문로2가,2층)",NaN,영화상영관,폐업,03,NaN,3,3.210336e+07,NaN,197428.923003,452041.177878,NaN,서울특별시 종로구 신문로2가 1-153 2층,1.0,NaN,3.0,NaN,4.0,2010-04-15,NaN,2022-03-25 13:09:35
1,3000000,CDFF4220002011000001,2011-03-23,NaN,폐업,2012-05-29,NaN,NaN,NaN,NaN,미로스페이스,I,문화시설,영화관,NaN,2026-05-10 22:41:08,"서울특별시 종로구 경희궁1길 1, 2층 (신문로2가, 가든플레이스)",NaN,영화상영관,폐업,03,NaN,3,3.210336e+07,NaN,197428.923003,452041.177878,NaN,서울특별시 종로구 신문로2가 1-153 가든플레이스 2층,3.0,NaN,1.0,NaN,4.0,2011-03-23,NaN,2012-06-08 14:44:56
2,3000000,CDFF4220002011000002,2011-05-23,NaN,폐업,2013-08-09,NaN,NaN,NaN,NaN,3D상상극장,I,근린생활시설,영화관,NaN,2026-05-10 22:41:09,"서울특별시 종로구 성균관로3길 20-4 (명륜3가,지하1층)",NaN,영화상영관,폐업,03,NaN,3,NaN,NaN,199666.948921,453452.586228,NaN,서울특별시 종로구 명륜3가 109-4 지하1층,3.0,NaN,1.0,NaN,4.0,2011-05-23,NaN,2013-08-09 16:53:32
3,3000000,CDFF4220002003000010,2003-02-12,NaN,영업/정상,NaN,NaN,NaN,NaN,4051.0,독립영화전용관 인디스페이스,I,NaN,영화관,NaN,2026-05-10 22:40:55,"서울특별시 마포구 양화로 176, 동교동 스타피카소 8층 (동교동)",영화상영관,영화상영관,영업중,13,NaN,1,7.082360e+09,NaN,193282.130800,450549.280167,NaN,서울특별시 마포구 동교동 166-14 동교동 스타피카소,NaN,NaN,NaN,NaN,NaN,2003-02-12,NaN,2022-02-21 11:00:52
4,3000000,CDFF4220002003000013,2003-02-12,NaN,영업/정상,NaN,NaN,NaN,NaN,NaN,허리우드클래식,I,NaN,영화관,NaN,2026-05-10 22:40:56,서울특별시 종로구 삼일대로 428 (낙원동),영화상영관,영화상영관,영업중,13,NaN,1,3.672423e+07,NaN,198852.959717,452253.942585,NaN,서울특별시 종로구 낙원동 284-6,NaN,NaN,NaN,NaN,NaN,2003-02-12,NaN,2020-03-23 14:02:25

In [7]:
columns = ["영업상태명","사업장명","도로명주소","데이터갱신시점","지번주소","지상층수"] # 필요한 컬럼만 가져오기
df[columns]                         # 확인
save_column_df = df[columns]        # 해당되는 컬럼만 보기    
len(save_column_df[save_column_df["영업상태명"] == "폐업"])         # 폐업한 영화관 건수

1457

In [8]:
len(save_column_df[save_column_df["영업상태명"] == "영업/정상"])     # 영업중인 영화관 건수

3510

In [45]:
len(save_column_df)     # 등록된 전체 영화관 건수

5233

In [9]:
save_column_df["영화관지역"] = save_column_df["지번주소"].str.split(" ").str[0]     # 지번주소 앞자리로 영화관 지역 구분
save_column_df

,영업상태명,사업장명,도로명주소,데이터갱신시점,지번주소,지상층수,영화관지역
0,폐업,독립영화전용관 시네마루,"서울특별시 종로구 경희궁1길 1 (신문로2가,2층)",2026-05-10 22:41:08,서울특별시 종로구 신문로2가 1-153 2층,1.0,서울특별시
1,폐업,미로스페이스,"서울특별시 종로구 경희궁1길 1, 2층 (신문로2가, 가든플레이스)",2026-05-10 22:41:08,서울특별시 종로구 신문로2가 1-153 가든플레이스 2층,3.0,서울특별시
2,폐업,3D상상극장,"서울특별시 종로구 성균관로3길 20-4 (명륜3가,지하1층)",2026-05-10 22:41:09,서울특별시 종로구 명륜3가 109-4 지하1층,3.0,서울특별시
3,영업/정상,독립영화전용관 인디스페이스,"서울특별시 마포구 양화로 176, 동교동 스타피카소 8층 (동교동)",2026-05-10 22:40:55,서울특별시 마포구 동교동 166-14 동교동 스타피카소,NaN,서울특별시
4,영업/정상,허리우드클래식,서울특별시 종로구 삼일대로 428 (낙원동),2026-05-10 22:40:56,서울특별시 종로구 낙원동 284-6,NaN,서울특별시
...,...,...,...,...,...,...,...
5228,폐업,롯데시네마 서귀포 2관,제주특별자치도 서귀포시 월드컵로 31 (법환동),2026-05-07 22:41:13,제주특별자치도 서귀포시 법환동 914,NaN,제주특별자치도
5229,영업/정상,시네메드자동차극장,NaN,2026-05-07 22:41:13,제주특별자치도 서귀포시 색달동 2889-1,NaN,제주특별자치도
5230,영업/정상,롯데시네마 서귀포 1관,제주특별자치도 서귀포시 월드컵로 31 (법환동),2026-05-07 22:41:13,제주특별자치도 서귀포시 법환동 914,NaN,제주특별자치도
5231,영업/정상,롯데시네마 서귀포2관,제주특별자치도 서귀포시 월드컵로 31 (법환동),2026-05-07 22:41:13,제주특별자치도 서귀포시 법환동 914,NaN,제주특별자치도
5232,영업/정상,롯데시네마 서귀포 3관,제주특별자치도 서귀포시 월드컵로 31 (법환동),2026-05-07 22:41:13,제주특별자치도 서귀포시 법환동 914,NaN,제주특별자치도

In [10]:
save_column_df["영화관지역"].value_counts(dropna=False) # dropna=False를 넣어야 NaN(결측치) 개수까지 함께 보입니다.

영화관지역
경기도          1353
서울특별시         947
전남광주통합특별시     394
부산광역시         318
경상남도          317
인천광역시         279
대구광역시         254
전북특별자치도       217
경상북도          207
충청남도          206
강원특별자치도       189
충청북도          184
대전광역시         161
울산광역시          96
제주특별자치도        81
세종특별자치시        26
0-0             1
408-196         1
광주광역시           1
전라북도            1
Name: count, dtype: int64

In [ ]:
save_column_df[save_column_df["영화관지역"] == '0-0']  # 이상 데이터 확인

     영업상태명 사업장명 도로명주소              데이터갱신시점  지번주소  지상층수 영화관지역
560  영업/정상  이상윤   NaN  2026-05-03 22:30:10  0-0    0.0   0-0

In [13]:
save_column_df[save_column_df["영화관지역"] == '408-196']

     영업상태명    사업장명 도로명주소              데이터갱신시점              지번주소  지상층수    영화관지역
561  영업/정상  시네마그래픽   NaN  2026-05-03 22:30:10  408-196 양천구 목1동    NaN  408-196

In [14]:
save_column_df = save_column_df.drop([560,561])

In [ ]:
save_column_df["영화관지역"].value_counts(dropna=False)         # 지역별 영화관수 확인

영화관지역
경기도          1353
서울특별시         947
전남광주통합특별시     394
부산광역시         318
경상남도          317
인천광역시         279
대구광역시         254
전북특별자치도       217
경상북도          207
충청남도          206
강원특별자치도       189
충청북도          184
대전광역시         161
울산광역시          96
제주특별자치도        81
세종특별자치시        26
광주광역시           1
전라북도            1
Name: count, dtype: int64

In [17]:
save_column_df.groupby("영화관지역")["사업장명"].count()

영화관지역
강원특별자치도       189
경기도          1353
경상남도          317
경상북도          207
광주광역시           1
대구광역시         254
대전광역시         161
부산광역시         318
서울특별시         947
세종특별자치시        26
울산광역시          96
인천광역시         279
전남광주통합특별시     394
전라북도            1
전북특별자치도       217
제주특별자치도        81
충청남도          206
충청북도          184
Name: 사업장명, dtype: int64

In [20]:
save_column_df.groupby(["영화관지역", "영업상태명"])["사업장명"].count().unstack()

영업상태명      영업/정상  취소/말소/만료/정지/중지     폐업    휴업
영화관지역
강원특별자치도    145.0             4.0   38.0   2.0
경기도        908.0            43.0  370.0  32.0
경상남도       206.0            14.0   97.0   NaN
경상북도       147.0             4.0   50.0   6.0
광주광역시        1.0             NaN    NaN   NaN
대구광역시      148.0             2.0   96.0   8.0
대전광역시      105.0             1.0   55.0   NaN
부산광역시      224.0             1.0   92.0   1.0
서울특별시      624.0            22.0  301.0   NaN
세종특별자치시     24.0             NaN    2.0   NaN
울산광역시       67.0             NaN   29.0   NaN
인천광역시      208.0            22.0   49.0   NaN
전남광주통합특별시  240.0             9.0  117.0  28.0
전라북도         1.0             NaN    NaN   NaN
전북특별자치도    129.0            33.0   47.0   8.0
제주특별자치도     46.0             9.0   26.0   NaN
충청남도       150.0            11.0   40.0   5.0
충청북도       135.0             NaN   48.0   1.0

In [21]:
save_column_df.groupby(["영화관지역", "영업상태명"])["사업장명"].count()

영화관지역      영업상태명
강원특별자치도    영업/정상             145
           취소/말소/만료/정지/중지      4
           폐업                 38
           휴업                  2
경기도        영업/정상             908
           취소/말소/만료/정지/중지     43
           폐업                370
           휴업                 32
경상남도       영업/정상             206
           취소/말소/만료/정지/중지     14
           폐업                 97
경상북도       영업/정상             147
           취소/말소/만료/정지/중지      4
           폐업                 50
           휴업                  6
광주광역시      영업/정상               1
대구광역시      영업/정상             148
           취소/말소/만료/정지/중지      2
           폐업                 96
           휴업                  8
대전광역시      영업/정상             105
           취소/말소/만료/정지/중지      1
           폐업                 55
부산광역시      영업/정상             224
           취소/말소/만료/정지/중지      1
           폐업                 92
           휴업                  1
서울특별시      영업/정상             624
           취소/말소/만료/정지/중지     22
           폐업                301
세종특별자치시    영업/정상              24
           폐업                  2
울산광역시      영업/정상              67
           폐업                 29
인천광역시      영업/정상             208
           취소/말소/만료/정지/중지     22
           폐업                 49
전남광주통합특별시  영업/정상             240
           취소/말소/만료/정지/중지      9
           폐업                117
           휴업                 28
전라북도       영업/정상               1
전북특별자치도    영업/정상             129
           취소/말소/만료/정지/중지     33
           폐업                 47
           휴업                  8
제주특별자치도    영업/정상              46
           취소/말소/만료/정지/중지      9
           폐업                 26
충청남도       영업/정상             150
           취소/말소/만료/정지/중지     11
           폐업                 40
           휴업                  5
충청북도       영업/정상             135
           폐업                 48
           휴업                  1
Name: 사업장명, dtype: int64

In [26]:
# 영화관 장사 안된다는데 지역별 영화관 영업 상태 현황 조사
save_column_df.groupby(["영화관지역", "영업상태명"])["사업장명"].count().reset_index().sort_values(["영화관지역","영업상태명"])

        영화관지역           영업상태명  사업장명
0     강원특별자치도           영업/정상   145
1     강원특별자치도  취소/말소/만료/정지/중지     4
2     강원특별자치도              폐업    38
3     강원특별자치도              휴업     2
4         경기도           영업/정상   908
5         경기도  취소/말소/만료/정지/중지    43
6         경기도              폐업   370
7         경기도              휴업    32
8        경상남도           영업/정상   206
9        경상남도  취소/말소/만료/정지/중지    14
10       경상남도              폐업    97
11       경상북도           영업/정상   147
12       경상북도  취소/말소/만료/정지/중지     4
13       경상북도              폐업    50
14       경상북도              휴업     6
15      광주광역시           영업/정상     1
16      대구광역시           영업/정상   148
17      대구광역시  취소/말소/만료/정지/중지     2
18      대구광역시              폐업    96
19      대구광역시              휴업     8
20      대전광역시           영업/정상   105
21      대전광역시  취소/말소/만료/정지/중지     1
22      대전광역시              폐업    55
23      부산광역시           영업/정상   224
24      부산광역시  취소/말소/만료/정지/중지     1
25      부산광역시              폐업    92
26      부산광역시              휴업     1
27      서울특별시           영업/정상   624
28      서울특별시  취소/말소/만료/정지/중지    22
29      서울특별시              폐업   301
30    세종특별자치시           영업/정상    24
31    세종특별자치시              폐업     2
32      울산광역시           영업/정상    67
33      울산광역시              폐업    29
34      인천광역시           영업/정상   208
35      인천광역시  취소/말소/만료/정지/중지    22
36      인천광역시              폐업    49
37  전남광주통합특별시           영업/정상   240
38  전남광주통합특별시  취소/말소/만료/정지/중지     9
39  전남광주통합특별시              폐업   117
40  전남광주통합특별시              휴업    28
41       전라북도           영업/정상     1
42    전북특별자치도           영업/정상   129
43    전북특별자치도  취소/말소/만료/정지/중지    33
44    전북특별자치도              폐업    47
45    전북특별자치도              휴업     8
46    제주특별자치도           영업/정상    46
47    제주특별자치도  취소/말소/만료/정지/중지     9
48    제주특별자치도              폐업    26
49       충청남도           영업/정상   150
50       충청남도  취소/말소/만료/정지/중지    11
51       충청남도              폐업    40
52       충청남도              휴업     5
53       충청북도           영업/정상   135
54       충청북도              폐업    48
55       충청북도              휴업     1