In [11]:
import chromadb

print(chromadb.__version__)

1.5.9

In [12]:
import pandas as pd
df = pd.read_csv("../data/98_restaurant_list_final_vector.csv").head(200).reset_index(drop=True)
df.head()

,번호,가게명_원본,주소_원본,검색확인명,주소_상호_검증,음식종류,대표메뉴,가게특징,추천상황,맛_스타일,...,따뜻한국물,가벼운식사,오늘뭐먹지_검색태그,오늘뭐먹지_추천문장,조사신뢰도,웹검증출처,네이버지도_재확인,카카오맵_재확인,조사일,벡터_오늘뭐먹지_검색태그
0,1,옛날황소곱창,서울 구로구 디지털로32나길 16 1층 (구로동),옛날황소곱창,주소/상호 확인,곱창·막창·대창,"곱창구이, 대창구이, 막창구이, 모듬구이, 특양구이, 곱창전골, 볶음밥",곱창구이 전문; 술모임; 회식; 저녁; 활기찬 분위기,"회식, 친구모임, 퇴근 후 술자리, 든든한 저녁","고소함, 진한맛, 구이, 뜨거움",...,○,X,"곱창, 막창, 대창, 회식, 친구모임, 퇴근 후 술자리, 든든한 저녁, 고소함, 진...",저녁에 음식과 술을 같이 즐기고 싶은 날,높음,https://www.diningcode.com/list.dc?query=%EC%9...,https://map.naver.com/p/search/%EC%98%9B%EB%82...,https://map.kakao.com/?q=%EC%98%9B%EB%82%A0%ED...,2026-09-14,"[0.021151810884475708, 0.008777650073170662, -..."
1,2,프레시랩 동작점,서울 동작구 국사봉2길 19 102호 (신대방동),프레시랩 동작점,주소/상호 확인,샐러드·건강식,"새우 리코타 샐러드, 단호박 리코타 샐러드, 샐러드류, 콜드브루",가벼운 식사; 채소 위주; 다이어트 식단; 포장하기 좋은 메뉴,"점심, 다이어트, 가볍게 먹기, 운동 전후","신선함, 담백함, 산뜻함, 차가운 메뉴",...,X,◎,"샐러드, 건강식, 점심, 다이어트, 가볍게 먹기, 운동 전후, 신선함, 담백함, 산...",가볍고 부담 적은 메뉴를 먹고 싶은 날,중간,https://search.naver.com/search.naver?query=%E...,https://map.naver.com/p/search/%ED%94%84%EB%A0...,https://map.kakao.com/?q=%ED%94%84%EB%A0%88%EC...,2026-09-14,"[0.0062872725538909435, -0.0176105797290802, -..."
2,3,유가네한우곰탕 본점,서울 동작구 국사봉1길 18 1층 (상도동),유가네한우곰탕 본점,주소/상호 확인,곰탕·국밥·해장국,"한우소머리곰탕, 곰탕, 돼지국밥, 뼈해장국, 설렁탕, 순대국, 육개장, 도가니탕",국물 메뉴 다양; 혼밥; 해장; 든든한 한 끼; 장시간 영업 정보 노출,"아침/점심, 혼밥, 해장, 추운 날, 든든하게","진한 국물, 구수함, 뜨끈함, 얼큰 선택 가능",...,◎,△,"곰탕, 국밥, 해장국, 아침, 점심, 혼밥, 해장, 추운 날, 든든하게, 진한 국물...",따뜻한 국물 한 끼가 당기는 날,높음,https://search.naver.com/search.naver?query=%E...,https://map.naver.com/p/search/%EC%9C%A0%EA%B0...,https://map.kakao.com/?q=%EC%9C%A0%EA%B0%80%EB...,2026-09-14,"[0.010547537356615067, -0.04264865070581436, -..."
3,4,모스키친,서울 동작구 보라매로 91 1층 (신대방동),모스키친,주소/상호 확인,돈카츠·일식,"등심카츠, 안심카츠, 특등심카츠",돈카츠 전문; 바 좌석; 깔끔한 분위기; 혼밥; 데이트,"점심, 혼밥, 데이트, 바삭한 메뉴가 당길 때","바삭함, 육즙, 담백함, 고소함",...,X,△,"돈카츠, 일식, 점심, 혼밥, 데이트, 바삭한 메뉴가 당길 때, 바삭함, 육즙, 담...",돈카츠·일식 메뉴가 당기는 날,높음,https://www.dongjak.go.kr/healthcare/main/cont...,https://map.naver.com/p/search/%EB%AA%A8%EC%8A...,https://map.kakao.com/?q=%EB%AA%A8%EC%8A%A4%ED...,2026-09-14,"[0.0026809086557477713, -0.04788929969072342, ..."
4,5,주성이네,서울 동작구 여의대방로22길 121 보라매자이 더 포레스트 상가,주성이네,상가 내 호수 정보 검색 확인,포차·닭도리탕·술안주,"대왕대창닭도리탕, 매운스지조림",신생 포차; 안주 중심; 편안한 분위기; 주차 가능 정보; 포장,"퇴근 후 술자리, 친구모임, 매운 안주, 저녁","매콤함, 진한 양념, 뜨거움, 술안주",...,○,X,"포차, 닭도리탕, 술안주, 퇴근 후 술자리, 친구모임, 매운 안주, 저녁, 매콤함,...",저녁에 음식과 술을 같이 즐기고 싶은 날,높음,https://postmate.waffle-gl.org/link/detail/brk...,https://map.naver.com/p/search/%EC%A3%BC%EC%84...,https://map.kakao.com/?q=%EC%A3%BC%EC%84%B1%EC...,2026-09-14,"[-0.0033457144163548946, -0.012418130412697792..."

In [13]:
import os
import chromadb
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction  # chromaDB 에서 Openai 임베딩 모델
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()   # .env 파일에 저장되어있는 api 키 가져오기
client = OpenAI()

In [14]:
embeddings = OpenAIEmbeddingFunction(
    model_name="text-embedding-3-small"
)

embed_client = chromadb.Client()

# collection 
collection = embed_client.get_or_create_collection(
    name="news_collection",
    embedding_function=embeddings,
    configuration={'hnsw' : {"space" : "cosine"}}
)

In [15]:
df.head()

,번호,가게명_원본,주소_원본,검색확인명,주소_상호_검증,음식종류,대표메뉴,가게특징,추천상황,맛_스타일,...,따뜻한국물,가벼운식사,오늘뭐먹지_검색태그,오늘뭐먹지_추천문장,조사신뢰도,웹검증출처,네이버지도_재확인,카카오맵_재확인,조사일,벡터_오늘뭐먹지_검색태그
0,1,옛날황소곱창,서울 구로구 디지털로32나길 16 1층 (구로동),옛날황소곱창,주소/상호 확인,곱창·막창·대창,"곱창구이, 대창구이, 막창구이, 모듬구이, 특양구이, 곱창전골, 볶음밥",곱창구이 전문; 술모임; 회식; 저녁; 활기찬 분위기,"회식, 친구모임, 퇴근 후 술자리, 든든한 저녁","고소함, 진한맛, 구이, 뜨거움",...,○,X,"곱창, 막창, 대창, 회식, 친구모임, 퇴근 후 술자리, 든든한 저녁, 고소함, 진...",저녁에 음식과 술을 같이 즐기고 싶은 날,높음,https://www.diningcode.com/list.dc?query=%EC%9...,https://map.naver.com/p/search/%EC%98%9B%EB%82...,https://map.kakao.com/?q=%EC%98%9B%EB%82%A0%ED...,2026-09-14,"[0.021151810884475708, 0.008777650073170662, -..."
1,2,프레시랩 동작점,서울 동작구 국사봉2길 19 102호 (신대방동),프레시랩 동작점,주소/상호 확인,샐러드·건강식,"새우 리코타 샐러드, 단호박 리코타 샐러드, 샐러드류, 콜드브루",가벼운 식사; 채소 위주; 다이어트 식단; 포장하기 좋은 메뉴,"점심, 다이어트, 가볍게 먹기, 운동 전후","신선함, 담백함, 산뜻함, 차가운 메뉴",...,X,◎,"샐러드, 건강식, 점심, 다이어트, 가볍게 먹기, 운동 전후, 신선함, 담백함, 산...",가볍고 부담 적은 메뉴를 먹고 싶은 날,중간,https://search.naver.com/search.naver?query=%E...,https://map.naver.com/p/search/%ED%94%84%EB%A0...,https://map.kakao.com/?q=%ED%94%84%EB%A0%88%EC...,2026-09-14,"[0.0062872725538909435, -0.0176105797290802, -..."
2,3,유가네한우곰탕 본점,서울 동작구 국사봉1길 18 1층 (상도동),유가네한우곰탕 본점,주소/상호 확인,곰탕·국밥·해장국,"한우소머리곰탕, 곰탕, 돼지국밥, 뼈해장국, 설렁탕, 순대국, 육개장, 도가니탕",국물 메뉴 다양; 혼밥; 해장; 든든한 한 끼; 장시간 영업 정보 노출,"아침/점심, 혼밥, 해장, 추운 날, 든든하게","진한 국물, 구수함, 뜨끈함, 얼큰 선택 가능",...,◎,△,"곰탕, 국밥, 해장국, 아침, 점심, 혼밥, 해장, 추운 날, 든든하게, 진한 국물...",따뜻한 국물 한 끼가 당기는 날,높음,https://search.naver.com/search.naver?query=%E...,https://map.naver.com/p/search/%EC%9C%A0%EA%B0...,https://map.kakao.com/?q=%EC%9C%A0%EA%B0%80%EB...,2026-09-14,"[0.010547537356615067, -0.04264865070581436, -..."
3,4,모스키친,서울 동작구 보라매로 91 1층 (신대방동),모스키친,주소/상호 확인,돈카츠·일식,"등심카츠, 안심카츠, 특등심카츠",돈카츠 전문; 바 좌석; 깔끔한 분위기; 혼밥; 데이트,"점심, 혼밥, 데이트, 바삭한 메뉴가 당길 때","바삭함, 육즙, 담백함, 고소함",...,X,△,"돈카츠, 일식, 점심, 혼밥, 데이트, 바삭한 메뉴가 당길 때, 바삭함, 육즙, 담...",돈카츠·일식 메뉴가 당기는 날,높음,https://www.dongjak.go.kr/healthcare/main/cont...,https://map.naver.com/p/search/%EB%AA%A8%EC%8A...,https://map.kakao.com/?q=%EB%AA%A8%EC%8A%A4%ED...,2026-09-14,"[0.0026809086557477713, -0.04788929969072342, ..."
4,5,주성이네,서울 동작구 여의대방로22길 121 보라매자이 더 포레스트 상가,주성이네,상가 내 호수 정보 검색 확인,포차·닭도리탕·술안주,"대왕대창닭도리탕, 매운스지조림",신생 포차; 안주 중심; 편안한 분위기; 주차 가능 정보; 포장,"퇴근 후 술자리, 친구모임, 매운 안주, 저녁","매콤함, 진한 양념, 뜨거움, 술안주",...,○,X,"포차, 닭도리탕, 술안주, 퇴근 후 술자리, 친구모임, 매운 안주, 저녁, 매콤함,...",저녁에 음식과 술을 같이 즐기고 싶은 날,높음,https://postmate.waffle-gl.org/link/detail/brk...,https://map.naver.com/p/search/%EC%A3%BC%EC%84...,https://map.kakao.com/?q=%EC%A3%BC%EC%84%B1%EC...,2026-09-14,"[-0.0033457144163548946, -0.012418130412697792..."

In [16]:
ids = df.index.astype(str).tolist()
metadata = df[['주소_원본', '검색확인명']].to_dict('records')
metadata

[{'주소_원본': '서울 구로구 디지털로32나길 16 1층 (구로동)', '검색확인명': '옛날황소곱창'},
 {'주소_원본': '서울 동작구 국사봉2길 19 102호 (신대방동)', '검색확인명': '프레시랩 동작점'},
 {'주소_원본': '서울 동작구 국사봉1길 18 1층 (상도동)', '검색확인명': '유가네한우곰탕 본점'},
 {'주소_원본': '서울 동작구 보라매로 91 1층 (신대방동)', '검색확인명': '모스키친'},
 {'주소_원본': '서울 동작구 여의대방로22길 121 보라매자이 더 포레스트 상가', '검색확인명': '주성이네'},
 {'주소_원본': '서울 동작구 여의대방로24길 140 1층 (신대방동)', '검색확인명': '기계우동'},
 {'주소_원본': '서울 동작구 여의대방로24길 141 2층 (대방동)', '검색확인명': '엉터리생고기 무한리필 신대방삼거리점'},
 {'주소_원본': '서울 동작구 보라매로 113 코스모빌딩 2층 203호 (대방동)', '검색확인명': '탕화쿵푸마라탕 대방점'},
 {'주소_원본': '서울 동작구 여의대방로24길 16 1층 (신대방동)', '검색확인명': '서일순대국 별관'},
 {'주소_원본': '서울 동작구 여의대방로24길 137 2층 (대방동)', '검색확인명': '동화장'},
 {'주소_원본': '서울 동작구 국사봉1길 45 1층 103호 (상도동)', '검색확인명': '만두의정석'},
 {'주소_원본': '서울 관악구 보라매로3길 8 1층 (봉천동)', '검색확인명': '청티엔'},
 {'주소_원본': '서울 동작구 보라매로5길 15 전문건설회관 지하1층', '검색확인명': '서평면옥'},
 {'주소_원본': '서울 동작구 상도로 54 1층 (대방동)', '검색확인명': '뭉텅 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 보라매로 96-1 1층 (신대방동)', '검색확인명': '단길'},
 {'주소_원본': '서울 동작구 국사봉길 13 1층 (상도동)', '검색확인명': '품미'},
 {'주소_원본': '서울 동작구 상도로12길 5-4 유천빌딩 1층 (상도동)', '검색확인명': '인생곱창'},
 {'주소_원본': '서울 동작구 상도로12길 7 1층 (상도동)', '검색확인명': '서민준밀밭'},
 {'주소_원본': '서울 동작구 상도로12길 20 (대방동)', '검색확인명': '원조부안집 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 상도로 77 1층 (대방동)', '검색확인명': '샐러디 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 보라매로 96 1층 (신대방동)', '검색확인명': '오다 신대방삼거리점'},
 {'주소_원본': '서울 동작구 보라매로 98 1층 (신대방동)', '검색확인명': '초밥24 신대방점'},
 {'주소_원본': '서울 동작구 국사봉1길 18 1층 1002-1호 (상도동)', '검색확인명': '차오야끼'},
 {'주소_원본': '서울 동작구 대방동길 7 1층 (대방동)', '검색확인명': '빨강돼지'},
 {'주소_원본': '서울 동작구 국사봉길 12 1층 105호 (신대방동)', '검색확인명': '상도감자탕'},
 {'주소_원본': '서울 동작구 보라매로 80 1층 (신대방동)', '검색확인명': '시간을들이다 본점'},
 {'주소_원본': '서울 동작구 여의대방로24길 66 1층 (신대방동)', '검색확인명': 'Moo Moo'},
 {'주소_원본': '서울 동작구 여의대방로24길 70 2층 (신대방동)', '검색확인명': '오다'},
 {'주소_원본': '서울 동작구 여의대방로22길 98 1층 (신대방동)', '검색확인명': '쌍둥이네 풍천장어'},
 {'주소_원본': '서울 동작구 여의대방로22길 80 1층 (신대방동)', '검색확인명': '이고집주꾸미'},
 {'주소_원본': '서울 동작구 보라매로 65 1층 (신대방동)', '검색확인명': '천안문'},
 {'주소_원본': '서울 동작구 보라매로 73 1층 (신대방동)', '검색확인명': '풀향기손칼국수'},
 {'주소_원본': '서울 동작구 보라매로 83 상가 1층 103호 (신대방동)', '검색확인명': '포케포케'},
 {'주소_원본': '서울 동작구 보라매로 113 1층 (대방동)', '검색확인명': '유태우스시'},
 {'주소_원본': '서울 동작구 여의대방로22길 121 보라매자이 더 포레스트 상가', '검색확인명': '뱃살도둑 신대방삼거리점'},
 {'주소_원본': '서울 동작구 여의대방로22길 138 1층 (신대방동)', '검색확인명': '꿈꾸는돼지 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 여의대방로22길 121 1층 1431호 (신대방동)', '검색확인명': '숲'},
 {'주소_원본': '서울 동작구 보라매로19길 25 1층 101호 (신대방동)', '검색확인명': '미분당 신대방삼거리점'},
 {'주소_원본': '서울 동작구 보라매로 99 1층 (신대방동)', '검색확인명': '88돼패쌈밥'},
 {'주소_원본': '서울 동작구 보라매로 93 1층 (신대방동)',
  '검색확인명': '이을 (과거 검색 정보) / 현재 동일 주소 다른 업장 가능성'},
 {'주소_원본': '서울 동작구 보라매로 93 1층 (신대방동)', '검색확인명': '피자스쿨 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 국사봉2길 22 1층 (신대방동)', '검색확인명': '채가네부대찌개돈까스'},
 {'주소_원본': '서울 동작구 국사봉1길 41 1층 (상도동)', '검색확인명': '이가초밥'},
 {'주소_원본': '서울 동작구 국사봉1길 41 1층 (상도동)', '검색확인명': '스미비부타동'},
 {'주소_원본': '서울 동작구 국사봉1길 12-5 1층 (상도동)', '검색확인명': '카츠 디나인(카츠 D9)'},
 {'주소_원본': '서울 동작구 국사봉1길 11 대룡빌딩 1층 (상도동)', '검색확인명': '포안베트남쌀국수'},
 {'주소_원본': '서울 동작구 상도로 77 1층 (대방동)', '검색확인명': '즉석손바지락칼국수'},
 {'주소_원본': '서울 동작구 대방동길 9 1층 102호 (대방동)', '검색확인명': '오늘스시해'},
 {'주소_원본': '서울 동작구 상도로 59 리안 1층 101호 (대방동)', '검색확인명': '프랭크버거 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 상도로 62 칸타빌레 1층 101호 (대방동)', '검색확인명': '버거리 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 여의대방로24길 129 더킴벌리빌딩 1층', '검색확인명': '샤브로21 신대방삼거리'},
 {'주소_원본': '서울 동작구 여의대방로22길 121 보라매자이 더 포레스트 상가', '검색확인명': '한제소곱창전골 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 여의대방로22길 121 보라매자이 더 포레스트 상가', '검색확인명': '마라홀릭 신대방점'},
 {'주소_원본': '서울 동작구 여의대방로22길 121 보라매자이 더 포레스트 상가', '검색확인명': '윤윤차이나'},
 {'주소_원본': '서울 동작구 여의대방로22길 121 보라매자이 더 포레스트 상가',
  '검색확인명': '고향엄마손생바지락칼국수 신대방삼거리점'},
 {'주소_원본': '서울 동작구 여의대방로22길 121 보라매자이 더 포레스트 상가', '검색확인명': '미태리 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 여의대방로24길 107 1층 (대방동)', '검색확인명': '네모오징어 신대방삼거리역점'},
 {'주소_원본': '서울 동작구 여의대방로24길 97 1층 (대방동)', '검색확인명': '한식부페셀프식당/한식뷔페셀프식당'},
 {'주소_원본': '서울 동작구 여의대방로24길 73 1층 102호 (대방동)', '검색확인명': '자주피자'}]

In [17]:
print(len(ids))

59

In [18]:
docs = df['오늘뭐먹지_추천문장'].tolist()

print(len(docs))

59

In [19]:
collection.upsert(ids=ids, documents=docs, metadatas=metadata)
collection.count()

59

In [20]:
question = "오늘 뭐 먹지?"

result = collection.query(query_texts=[question], n_results=5)
result

{'ids': [['40', '48', '49', '58', '10']],
 'embeddings': None,
 'documents': [['간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
   '간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
   '간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
   '간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
   '가볍고 부담 적은 메뉴를 먹고 싶은 날']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'검색확인명': '피자스쿨 신대방삼거리역점',
    '주소_원본': '서울 동작구 보라매로 93 1층 (신대방동)'},
   {'주소_원본': '서울 동작구 상도로 59 리안 1층 101호 (대방동)', '검색확인명': '프랭크버거 신대방삼거리역점'},
   {'주소_원본': '서울 동작구 상도로 62 칸타빌레 1층 101호 (대방동)', '검색확인명': '버거리 신대방삼거리역점'},
   {'검색확인명': '자주피자', '주소_원본': '서울 동작구 여의대방로24길 73 1층 102호 (대방동)'},
   {'검색확인명': '만두의정석', '주소_원본': '서울 동작구 국사봉1길 45 1층 103호 (상도동)'}]],
 'distances': [[0.5904224514961243,
   0.590502142906189,
   0.590502142906189,
   0.590502142906189,
   0.6423448324203491]]}

In [16]:
result['documents'][0]

['간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
 '간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
 '간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
 '간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
 '가볍고 부담 적은 메뉴를 먹고 싶은 날']

In [21]:
persistant_client = chromadb.PersistentClient(path="restaurant_list_chroma_db")

In [27]:
import chromadb
import os
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction  # chromaDB 에서 Openai 임베딩 모델
from dotenv import load_dotenv
from openai import OpenAI


embeddings = OpenAIEmbeddingFunction(
    model_name="text-embedding-3-small"
)

saved_collection = persistant_client.get_or_create_collection(
    name="restaurant_list",
    embedding_function=embeddings,
    configuration={"hnsw": {"space":"cosine"} }
)

In [28]:
saved_collection.upsert(ids=ids,
                        documents=docs,
                        metadatas=metadata
                        )

In [24]:
load_client = chromadb.PersistentClient(path="restaurant_list_chroma_db")
load_collection = load_client.get_collection(
    name="restaurant_list",
    embedding_function=embeddings       # 임베딩 모델을 뭘 썼는지
)

In [29]:
load_collection.query(query_texts=['간짜장'], n_results=4)

{'ids': [['58', '40', '48', '49']],
 'embeddings': None,
 'documents': [['간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
   '간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
   '간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날',
   '간단하고 익숙한 메뉴로 빠르게 먹고 싶은 날']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'주소_원본': '서울 동작구 여의대방로24길 73 1층 102호 (대방동)', '검색확인명': '자주피자'},
   {'검색확인명': '피자스쿨 신대방삼거리역점', '주소_원본': '서울 동작구 보라매로 93 1층 (신대방동)'},
   {'검색확인명': '프랭크버거 신대방삼거리역점', '주소_원본': '서울 동작구 상도로 59 리안 1층 101호 (대방동)'},
   {'주소_원본': '서울 동작구 상도로 62 칸타빌레 1층 101호 (대방동)', '검색확인명': '버거리 신대방삼거리역점'}]],
 'distances': [[0.6420385837554932,
   0.6420516967773438,
   0.6421518921852112,
   0.6421518921852112]]}