In [2]:
import pandas as pd

df = pd.read_csv("../data/07-1_study_habits.csv")
df.head()

   반 성별  공부시간  시험점수     용돈
0  C  여   2.7    63  11000
1  A  남   1.8    69  23000
2  C  남   3.5    74  27000
3  C  여   2.0    74   6000
4  A  여   3.2    64  25000

### 2.중심- 평균,중앙값,최빈값

In [10]:
print("평균:", df["시험점수"].mean() )        # 평균
print("중앙값:", df["시험점수"].median())     # 중앙값
print("최빈값:", df["시험점수"].mode())       # 최빈값

평균: 70.0
중앙값: 69.0
최빈값: 0    69
Name: 시험점수, dtype: int64

In [ ]:
mean_value = df["시험점수"].mean()
print("평균:", mean_value)

평균: 70.0

In [12]:
median_value = df["시험점수"].median()
print(median_value)

69.0

In [14]:
mode_value = df["시험점수"].mode()[0]
print(mode_value)

69

In [ ]:
# mean 직접 구하기
total_score = df["시험점수"].sum()
print(total_score)

8400

In [17]:
total_score / df['시험점수'].count()

np.float64(70.0)

In [18]:
# 평균과 중앙이 다른경우 
df['용돈'].mean()

np.float64(30658.333333333332)

In [19]:
df["용돈"].median()

np.float64(23500.0)

### 4. 범위, 분산, 표준편차
- 범위 : 최댓값 ~ 최솟값
- 분산, 표준편차: 평균에서 얼마나 떨어져 있는지 보는 통곗값

In [20]:
score = df["시험점수"]
print("최댓값", score.max())
print("최솟값", score.min())
print("범위", score.max() -score.min() )

최댓값 100
최솟값 46
범위 54

In [21]:
df.describe()

             공부시간        시험점수             용돈
count  120.000000  120.000000     120.000000
mean     3.485833   70.000000   30658.333333
std      2.452517   12.470469   23129.702187
min      0.300000   46.000000    5000.000000
25%      1.700000   62.000000   17000.000000
50%      2.900000   69.000000   23500.000000
75%      4.600000   77.000000   38000.000000
max     12.400000  100.000000  142000.000000

In [23]:
df.describe()['시험점수']["25%"]

np.float64(62.0)

In [25]:
df.describe().loc["25%"]["시험점수"]

np.float64(62.0)

In [27]:
# 사분위 수로 직접 구해보기
df['시험점수'].quantile([0.25,0.5])

0.25    62.0
0.50    69.0
Name: 시험점수, dtype: float64

In [28]:
df['시험점수'].quantile([0.75])

0.75    77.0
Name: 시험점수, dtype: float64

In [29]:
df.describe()

             공부시간        시험점수             용돈
count  120.000000  120.000000     120.000000
mean     3.485833   70.000000   30658.333333
std      2.452517   12.470469   23129.702187
min      0.300000   46.000000    5000.000000
25%      1.700000   62.000000   17000.000000
50%      2.900000   69.000000   23500.000000
75%      4.600000   77.000000   38000.000000
max     12.400000  100.000000  142000.000000