### 1. 임베딩
- 텍스트를 문장 단위로 벡터 : [0.25, 01.12, 0.11] 이런식으로 변환
- 검색, 추천시스템, RAG(챗봇), 분류 -> 이 벡터 변환 방식을 씁니다.

### 2. 임베팅 모델 준비
- 한국어에 강한 최신 모델 - 작고 빠른 걸로 - CPU 도 가능한

In [6]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("dragonkue/multilingual-e5-small-ko-v2")
print("모델 준비 완료")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

모델 준비 완료

### E5 - 모델 사용법 익히기
- query : 질문 입력할 때
- passage : 검색 대상이 되는 문서

In [4]:
sentence = "오늘 점심 메뉴는?"
with_prefix = model.encode("query:" + sentence, normalize_embeddings=True) # normalize_embeddings=
without_prefix = model.encode(sentence, normalize_embeddings=True) 

print("접두사가 있을때",with_prefix[:10])
print("접두사가 있을때",without_prefix[:10])

접두사가 있을때 [ 0.03057274 -0.00737129 -0.09526572  0.01687642  0.07531504 -0.04751493
  0.03268289  0.01705527  0.04623772  0.063585  ]
접두사가 있을때 [ 0.02251527 -0.00308811 -0.0859407   0.00292922  0.088636   -0.04761829
  0.04911163  0.01086638  0.05150406  0.07169256]

In [7]:
sentence = ["오늘 점심으로 무엇을 먹을까요?",
            "점심 메뉴를 추천해주세요",
            "오늘 점심은 김치찌개가 어때요",
            "저녁에는 어떤거 먹을까요",    
            "오늘 영화 보러 갈까?",
            "파이썬 공부 너무 재밌어요?",
            "인공지능 개발 재밌나?"
            ]

vecs = model.encode(
    ["query: " + text for text in sentence],
    normalize_embeddings=True
)

In [13]:
vecs.shape

(7, 384)

In [20]:
import pandas as pd

df = pd.read_csv("../data/11-1_뉴스정제.csv")
# df['정제본문'][0]

article_vec = model.encode("passage" + df['정제본문'][0], normalize_embeddings=True)

In [21]:
print(article_vec[:10])

[ 0.01755401  0.01300447 -0.03028799  0.05291676  0.00164915  0.02462793
 -0.07902569  0.03739966  0.01071625 -0.01512395]

In [ ]:
df['passage_add'] = df['정제본문']
df.head()

,제목,본문,카테고리,요약,출처URL,정제본문,passage_add
0,현대백화점그룹 더현대 광주 추진,서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복...,경제,"6 6일 현대백화점그룹이 광주시에 문화복합몰을 만든다고 6일 밝혔으며, 광주시는 서...",https://n.news.naver.com/mnews/article/001/001...,서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복...,passage: 서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울...
1,이스타항공 이상직 회사와 무관…오해 살 언동 말아야,전주 뉴시스 김얼 기자 이스타항공 자금 배임·횡령으로 전주교도소에 수감됐었던 이상직...,경제,이이스항공은 자금 배임·횡령으로 전주교도소에 수감됐었던 이상직 전 의원이 출소한 것...,https://n.news.naver.com/mnews/article/003/001...,전주 뉴시스 김얼 기자 이스타항공 자금 배임 횡령으로 전주교도소에 수감됐었던 이상직...,passage: 전주 뉴시스 김얼 기자 이스타항공 자금 배임 횡령으로 전주교도소에 ...
2,농협은행 농협금융 출범 10주년 기념주화 NFT 이벤트,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 ‘10주년 기념주...,경제,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 소셜미디어 인스타...,https://n.news.naver.com/mnews/article/366/000...,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 10주년 기념주화...,passage: NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 ...
3,오늘부터 유류세 인하 폭 확대…하반기 바뀌는 세제·금융 정책은,img tag s 지난 30일 서울의 한 주유소. 〈사진 연합뉴스〉 img tag ...,경제,정부는 고유가 상황에 따라 국민의 유류비 부담 완화를 위해 이날부터 유류세를 법정 ...,https://n.news.naver.com/mnews/article/437/000...,img tag s 지난 30일 서울의 한 주유소 사진 연합뉴스 img tag e 오...,passage: img tag s 지난 30일 서울의 한 주유소 사진 연합뉴스 im...
4,푸르덴셜생명 더 큰 드림 변액연금보험Ⅱ에 신규펀드 13종 추가,파이낸셜뉴스 푸르덴셜생명보험은 급변하는 금융시장에 대응하기 위해 무배당 더 큰 드림...,경제,지난르덴셜생명보험은 급변하는 금융시장에 대응하기 위해 무배당 더 큰 드림 변액연금보...,https://n.news.naver.com/mnews/article/014/000...,파이낸셜뉴스 푸르덴셜생명보험은 급변하는 금융시장에 대응하기 위해 무배당 더 큰 드림...,passage: 파이낸셜뉴스 푸르덴셜생명보험은 급변하는 금융시장에 대응하기 위해 무...

In [24]:
article_vec = model.encode(df['passage_add'].tolist()[:100], normalize_embeddings=True)
print(article_vec)

KeyboardInterrupt:

In [14]:
from sentence_transformers import util
import numpy as np

query = "경제 상황이 어떻게 되고 있어?"

def search_text(query, k=3):
    query_vec = model.encode(
        "query: " + query,
        normalize_embeddings=True
    )

    similarity = util.cos_sim(query_vec, article_vec)

    for i in similarity[0].argsort(descending=True)[:k]:
        index = i.item()

        print(
            similarity[0][index].item(),
            df["정제본문"].iloc[index]
        )

In [38]:
search_text(query)

0.5654933452606201 경제와이드 모닝벨 조간 브리핑 장연재 조간브리핑입니다 발길 끊는 개미들 거래대금 20개월만에 최저 동학개미들이 국내 주식시장을 떠나고 있다는 기사 먼저 보겠습니다 중앙일보입니다 미국발 금리 인상과 세계 경제 침체 우려로 올해에만 코스피가 20 넘게 급락하자 개인투자자들이 증시를 이탈하고 있습니다 코스피에서 개인 투자자의 하루 평균 거래 대금은 4조 3 009억 원으로 2년 4개월 만에 최저 수준을 기록했습니다 증시 대기자금인 투자자예탁금은 지난달 말 기준 반년 만에 10조 원이 줄었고 빚을 내 투자한 후 아직 갚지 않은 금액인 신용거래융자 잔고도 같은 기간 5조 원 이상 줄었습니다 이런 가운데 당분간 전 세계의 경기 침체 공포로 국내증시 반등을 기대하긴 어렵다는 의견이 지배적인데요 반면 일부 증권가에서는 기존 악재가 반영된 만큼 약세장을 오히려 기회로 삼아야 한다는 의견도 있습니다 지방 중심 역전세 깡통아파트 확산 경향신문 기사입니다 최근 지방의 저가 아파트를 중심으로 전세가격이 매매가격보다 높은 역전세 현상이 나타나고 있습니다 정부의 다주택자 규제 완화 조치 이후 매물이 쌓이고 있지만 금리가 오르자 집을 사려는 사람이 없어 집값은 하락하고 있습니다 반면 전세시장은 신규 계약체결 시점에 경신까지 염두에 두고 4년 치 상승분을 미리 가격에 반영하려는 경향이 있어서 역전세가 발생하고 있는 건데요 전세계약 시점에 집값이 이미 전세가격보다 낮다면 보증금을 보호받을 수 없어서 문제가 되고 있습니다 이런 현상은 현재까지 갭투자가 주로 이뤄지는 3억 원 이하 지방 저가 아파트에서 주로 나타나는데요 전문가들은 서울 집값은 큰 변화가 없기 때문에 전국적인 문제로 보기는 어렵다고 분석했습니다 경기 침체에 빅테크 감원 시작됐다 전 세계 기업에 감원 공포가 불고 있다는 조선일보 기사도 보겠습니다 코로나 팬데믹 기간 큰돈을 벌며 조직 규모를 키웠던 테크 기업들 너도나도 긴축 경영에 돌입하고 있습니다 인플레이션과 금리 인상 등으로 사업 환경이 급속도로 악화되고 있기 때문입니다 페이스북은 올해 신규 채용을 당초 계획보다 30 줄이기로 했고 테슬라는 정규직의 10 인 6 000여 명에 대해 해고를 예고했습니다 중국 빅테크 기업인 텐센트도 올 상반기 전체 인력의 10 15 인력을 감축했습니다 국내 대기업들도 타격이 불가피해 보이는데요 네이버는 올해 신규 채용을 작년보다 30 정도 줄인다는 계획입니다 수주 늘어도 속타는 조선업 설계인력 6년새 70 급감 매일경제 신문 기사입니다 13년여 만에 최대 수주 실적을 이어가고 있는 한국 조선 산업이 이중의 인력 부족 현상을 겪고 있습니다 당장 올해 하반기 늘어나는 건조 물량을 소화해낼 생산 인력이 부족하고 미래 성장 동력을 이끌 설계 연구개발 부문 인력도 과거의 절반 이하로 최저 수준을 유지하고 있습니다 장기간 지속된 불황으로 조선업계는 다른 산업 현장에 비해 처우가 낮고 불황 호황에 따른 온도 차가 커 고용 안정성이 낮은 탓입니다 결국 장기간 지속된 보릿고개 여파가 국내 조선 산업의 현재 미래 모두 발목을 잡고 있다는 우려가 커지고 있습니다 벌써 37 8도 찜통 장맛비 내릴 때까지 더위 견뎌야 한겨레 기사입니다 어제 3일 참 많이 더웠죠 서울 낮 최고 기온이 올여름 들어 가장 높은 34 2도를 기록했고 경기 시흥시 신형동에서 37 8도가 측정되는 등 전국이 폭염으로 몸살을 앓았습니다 폭염은 모레인 6일까지 이어질 것으로 보입니다 제4호 태풍 에어리 가 한반도를 비껴갔지만 고온다습한 공기가 유입되면서 강한 햇볕과 높은 습도에 의해 체감온도가 크게 오르고 있기 때문인데요 오늘 전국 대부분 지역에 폭염특보가 발효된 가운데 최고 체감온도가 35도 안팎까지 오르고 밤사이 열대야가 나타나는 곳이 있겠습니다 이번 더위는 물러났던 장맛비가 7일께 다시 찾아오면 한풀 꺾일 것으로 보입니다
0.5409510135650635 한은 우크라 사태 국내 물가 영향 원자재 해외 의존도 높은 산업 타격 러시아의 우크라이나 침공 중국 봉쇄 조치 등 최근 글로벌 공급망 차질이 기업의 비용 부담으로 이어져 이미 천정부지로 치솟는 물가 오름세가 더 커질 수 있다는 경고가 나왔다 공급망 차질이 지속되면 자동차와 2차전지 등 일부 업종은 생산에도 영향을 받을 것으로 보인다 한국은행은 4일 발표한 최근 글로벌 공급망 차질의 특징 및 국내 산업에 미치는 영향 보고서에서 우크라이나 사태 장기화 글로벌 식량 수급 불안 중국의 제로 코로나 정책 유지 등으로 향후 글로벌 공급망의 불확실성이 크다 며 이런 리스크가 현실화하면 대외 의존도가 높은 우리나라는 물가 오름세가 심화하고 생산에 대한 영향도 확대될 가능성이 있다 고 진단했다 보고서에 따르면 글로벌 공급망 차질로 인해 자동차 건설 기계장비 등 일부 산업은 부품 자재 수급 차질이 빚어져 생산이 일부 제약됐다 직접적인 생산 차질은 다른 국가들과 비교해 상대적으로 큰 편은 아니라는 게 한은의 설명이다 아울러 원자재 중간재 가격이 상승하면서 대부분 산업에서 비용 부담은 커졌다 실제로 생산단계별 물가를 보면 5월 기준으로 원재료는 1년 전보다 60 8 상승했고 중간재는 15 4 나 뛰었다 생산자물가 통계에서 공산품으로 분류된 품목 중 가격 상승률이 5 이상인 품목의 비중은 절반을 넘었고 가격 상승률이 10 이상인 품목은 약 40 에 달한다 생산자들이 제품을 만드는 데 드는 비용이 늘어난 만큼 앞으로 소비자물가에도 영향을 미칠 전망이다 MobileAdNew center 한은은 우크라이나 사태 등 공급망 차질이 길어지면 원자재 해외 의존도가 높은 우리 산업에 부정적인 영향을 미칠 것으로 봤다 보고서는 자동차 2차전지 등에 사용되는 주요 필수 소재인 마그네슘 희토류 리튬 등의 대중 의존도는 80 이상이며 크립톤 제논 팔라듐 등의 대러시아 우크라이나 의존도는 30 이상 이라며 글로벌 공급망 상황과 국내 산업의 취약성을 면밀히 점검하고 향후 글로벌 공급망의 재편에도 적극 대응해 나갈 필요가 있다 고 밝혔다
0.5389879941940308 유럽중앙은행 본부 건물 AFP 뉴스1 서울 뉴스1 박형기 기자 금리인상으로 인한 세계 경기 침체 우려가 지속되면서 유럽증시도 일제히 하락 출발하고 있다 1일 오후 4시20분 현재 한국시간 기준 독일의 닥스는 1 17 영국의 FTSE는 0 79 프랑스의 까그는 0 77 각각 하락하고 있다 범유럽지수인 스톡스600은 0 98 하락하고 있다 전일에도 유럽증시는 일제히 급락했었다 독일의 닥스가 1 69 영국의 FTSE가 1 96 프랑스의 까그지수가 1 80 각각 급락했다 범유럽지수인 스톡스600지수는 1 50 하락했다 이는 인플레이션 고조로 각국 중앙은행이 공격적인 금리인상에 나섬에 따라 글로벌 경기가 침체할 것이란 우려가 지속되고 있기 때문으로 풀이된다 앞서 마감한 아시아 증시도 같은 이유로 일제히 하락 마감했다 일본 닛케이가 1 73 한국 코스피가 1 17 호주 ASX지수가 0 43 중국 상하이종합지수가 0 32 각각 하락했다

In [40]:
query = "오늘 점심메뉴 뭐야?"
query = "요새 경제도 안좋은데 가격까지 고려한 오늘 점심 메뉴는 뭐야?"
search_text(query)

0.5097311735153198 경제와이드 모닝벨 조간 브리핑 장연재 조간브리핑입니다 발길 끊는 개미들 거래대금 20개월만에 최저 동학개미들이 국내 주식시장을 떠나고 있다는 기사 먼저 보겠습니다 중앙일보입니다 미국발 금리 인상과 세계 경제 침체 우려로 올해에만 코스피가 20 넘게 급락하자 개인투자자들이 증시를 이탈하고 있습니다 코스피에서 개인 투자자의 하루 평균 거래 대금은 4조 3 009억 원으로 2년 4개월 만에 최저 수준을 기록했습니다 증시 대기자금인 투자자예탁금은 지난달 말 기준 반년 만에 10조 원이 줄었고 빚을 내 투자한 후 아직 갚지 않은 금액인 신용거래융자 잔고도 같은 기간 5조 원 이상 줄었습니다 이런 가운데 당분간 전 세계의 경기 침체 공포로 국내증시 반등을 기대하긴 어렵다는 의견이 지배적인데요 반면 일부 증권가에서는 기존 악재가 반영된 만큼 약세장을 오히려 기회로 삼아야 한다는 의견도 있습니다 지방 중심 역전세 깡통아파트 확산 경향신문 기사입니다 최근 지방의 저가 아파트를 중심으로 전세가격이 매매가격보다 높은 역전세 현상이 나타나고 있습니다 정부의 다주택자 규제 완화 조치 이후 매물이 쌓이고 있지만 금리가 오르자 집을 사려는 사람이 없어 집값은 하락하고 있습니다 반면 전세시장은 신규 계약체결 시점에 경신까지 염두에 두고 4년 치 상승분을 미리 가격에 반영하려는 경향이 있어서 역전세가 발생하고 있는 건데요 전세계약 시점에 집값이 이미 전세가격보다 낮다면 보증금을 보호받을 수 없어서 문제가 되고 있습니다 이런 현상은 현재까지 갭투자가 주로 이뤄지는 3억 원 이하 지방 저가 아파트에서 주로 나타나는데요 전문가들은 서울 집값은 큰 변화가 없기 때문에 전국적인 문제로 보기는 어렵다고 분석했습니다 경기 침체에 빅테크 감원 시작됐다 전 세계 기업에 감원 공포가 불고 있다는 조선일보 기사도 보겠습니다 코로나 팬데믹 기간 큰돈을 벌며 조직 규모를 키웠던 테크 기업들 너도나도 긴축 경영에 돌입하고 있습니다 인플레이션과 금리 인상 등으로 사업 환경이 급속도로 악화되고 있기 때문입니다 페이스북은 올해 신규 채용을 당초 계획보다 30 줄이기로 했고 테슬라는 정규직의 10 인 6 000여 명에 대해 해고를 예고했습니다 중국 빅테크 기업인 텐센트도 올 상반기 전체 인력의 10 15 인력을 감축했습니다 국내 대기업들도 타격이 불가피해 보이는데요 네이버는 올해 신규 채용을 작년보다 30 정도 줄인다는 계획입니다 수주 늘어도 속타는 조선업 설계인력 6년새 70 급감 매일경제 신문 기사입니다 13년여 만에 최대 수주 실적을 이어가고 있는 한국 조선 산업이 이중의 인력 부족 현상을 겪고 있습니다 당장 올해 하반기 늘어나는 건조 물량을 소화해낼 생산 인력이 부족하고 미래 성장 동력을 이끌 설계 연구개발 부문 인력도 과거의 절반 이하로 최저 수준을 유지하고 있습니다 장기간 지속된 불황으로 조선업계는 다른 산업 현장에 비해 처우가 낮고 불황 호황에 따른 온도 차가 커 고용 안정성이 낮은 탓입니다 결국 장기간 지속된 보릿고개 여파가 국내 조선 산업의 현재 미래 모두 발목을 잡고 있다는 우려가 커지고 있습니다 벌써 37 8도 찜통 장맛비 내릴 때까지 더위 견뎌야 한겨레 기사입니다 어제 3일 참 많이 더웠죠 서울 낮 최고 기온이 올여름 들어 가장 높은 34 2도를 기록했고 경기 시흥시 신형동에서 37 8도가 측정되는 등 전국이 폭염으로 몸살을 앓았습니다 폭염은 모레인 6일까지 이어질 것으로 보입니다 제4호 태풍 에어리 가 한반도를 비껴갔지만 고온다습한 공기가 유입되면서 강한 햇볕과 높은 습도에 의해 체감온도가 크게 오르고 있기 때문인데요 오늘 전국 대부분 지역에 폭염특보가 발효된 가운데 최고 체감온도가 35도 안팎까지 오르고 밤사이 열대야가 나타나는 곳이 있겠습니다 이번 더위는 물러났던 장맛비가 7일께 다시 찾아오면 한풀 꺾일 것으로 보입니다
0.5074411630630493 유류세 인하 폭이 37 로 확대 적용된 1일 오후 서울 서초구 서울만남의광장 휴게소 주유소에 주유를 위해 대기중인 차량이 줄지어 서 있다 유류세 인하로 이 주유소에서는 휘발유가 리터당 2068원 경유가 2152원으로 판매되고 있다 이날 오전 9시 기준 전국 평균 휘발유 가격은 전날보다 11 37원 내린 리터당 2133 53원을 나타냈다 전국 평균 경유 가격도 전날보다 7 38원 내린 2160 28원을 기록했다 사진영상기획부 발로 뛰는 더팩트는 24시간 여러분의 제보를 기다립니다
0.49765676259994507 한은 우크라 사태 국내 물가 영향 원자재 해외 의존도 높은 산업 타격 러시아의 우크라이나 침공 중국 봉쇄 조치 등 최근 글로벌 공급망 차질이 기업의 비용 부담으로 이어져 이미 천정부지로 치솟는 물가 오름세가 더 커질 수 있다는 경고가 나왔다 공급망 차질이 지속되면 자동차와 2차전지 등 일부 업종은 생산에도 영향을 받을 것으로 보인다 한국은행은 4일 발표한 최근 글로벌 공급망 차질의 특징 및 국내 산업에 미치는 영향 보고서에서 우크라이나 사태 장기화 글로벌 식량 수급 불안 중국의 제로 코로나 정책 유지 등으로 향후 글로벌 공급망의 불확실성이 크다 며 이런 리스크가 현실화하면 대외 의존도가 높은 우리나라는 물가 오름세가 심화하고 생산에 대한 영향도 확대될 가능성이 있다 고 진단했다 보고서에 따르면 글로벌 공급망 차질로 인해 자동차 건설 기계장비 등 일부 산업은 부품 자재 수급 차질이 빚어져 생산이 일부 제약됐다 직접적인 생산 차질은 다른 국가들과 비교해 상대적으로 큰 편은 아니라는 게 한은의 설명이다 아울러 원자재 중간재 가격이 상승하면서 대부분 산업에서 비용 부담은 커졌다 실제로 생산단계별 물가를 보면 5월 기준으로 원재료는 1년 전보다 60 8 상승했고 중간재는 15 4 나 뛰었다 생산자물가 통계에서 공산품으로 분류된 품목 중 가격 상승률이 5 이상인 품목의 비중은 절반을 넘었고 가격 상승률이 10 이상인 품목은 약 40 에 달한다 생산자들이 제품을 만드는 데 드는 비용이 늘어난 만큼 앞으로 소비자물가에도 영향을 미칠 전망이다 MobileAdNew center 한은은 우크라이나 사태 등 공급망 차질이 길어지면 원자재 해외 의존도가 높은 우리 산업에 부정적인 영향을 미칠 것으로 봤다 보고서는 자동차 2차전지 등에 사용되는 주요 필수 소재인 마그네슘 희토류 리튬 등의 대중 의존도는 80 이상이며 크립톤 제논 팔라듐 등의 대러시아 우크라이나 의존도는 30 이상 이라며 글로벌 공급망 상황과 국내 산업의 취약성을 면밀히 점검하고 향후 글로벌 공급망의 재편에도 적극 대응해 나갈 필요가 있다 고 밝혔다

In [41]:
query = "금리 인상 관련해서 알려줘"
search_text(query,5)

0.593738317489624 예대금리차 7년 7개월만에 가장 큰 폭으로 늘어 은행들 여론 악화 부담 느껴 이미지출처 연합뉴스 정치권과 금융당국의 이자장사 경고에 시중은행들이 대출금리를 계속 낮추고 정기 예 적금 상품의 금리는 특판 등을 통해 연 3 5 대까지 올리고 있다 대출금리와 예대금리 간의 차이인 의미하는 예대금리차가 7년 7개월 만에 가장 큰 폭으로 벌어지자 여론이 악화돼 은행들이 부담을 느낀 것도 이런 조치를 내린 이유다 3일 금융권에 따르면 신한은행은 이르면 이번주 4 8일 부터 신규 취급 주택담보대출과 전세자금대출 금리를 각각 최대 0 35 포인트 p 0 30 p 내리기로 했다 취약 차주 프로그램 도 이달 초 시작할 예정이다 우선 6월말 기준 연 5 가 넘는 금리로 주택담보대출을 이용하는 차주의 금리를 1년간 연 5 로 일괄 인하하고 5 초과분은 은행이 대신 지원해주기로 했다 금리상한형 주택담보대출 연간 금리 상승폭 0 75 포인트 이내로 제한한 상품 을 신청하는 대출자에게는 원래 고객이 부담해야하는 연 0 2 p의 가산금리를 신한은행이 1년간 내주기로 했다 전세자금대출자 중 연소득 4000만원 이하 전세보증금 3억원 이하 의 조건을 갖춘 이들을 대상으로 금융채 2년물 금리를 기준으로 삼는 전세자금대출 상품도 내놓는다 전세자금대출은 일보통 6개월 또는 1년 단위 변동금리 상품인데 사실상 2년 단위 고정금리 상품을 내놔 금리 상승에 따른 위험을 낮추겠다는 의미다 신한은행은 더불어 대표적 서민 지원 금융상품인 새희망홀씨 대출의 신규 금리도 연 0 5 p 내릴 방침이다 NH농협은행은 이달 1일부터 우대금리 확대 등을 통해 담보 전세자금 등 주택관련대출 금리를 0 1 0 2 p 낮췄다 우리은행 역시 지난달 24일부터 은행채 5년물 기준 고정금리 대출에 적용하던 1 3 p의 우대금리 은행 자체 신용등급 7등급 이내 를 모든 등급 8 10등급 추가 에 한꺼번에 주기로 했다 우리은행 전체 등급의 가산금리가 1 5 p씩 낮아진 것과 마찬가지다 케이뱅크도 같은 달 22일 대출금리를 최대 연 0 41 포인트 인하했다 한편 은행들의 예금금리는 오르는 중이다 신한은행은 지난 1일 창업 40주년 을 맞아 특판 상품인 신한 40주년 페스타 적금 과 신한 S드림 정기예금 을 출시했다 10만 계좌 한도로 출시된 페스타 적금은 주 단위로 납입하는 만기 10개월 자유 적금으로 월 최대 30만원까지 납입할 수 있고 최고 금리가 연 4 0 에 이른다 NH농협도 오는 11일께 우대금리 0 4 p를 포함해 금리가 연 3 대인 정기예금 신상품을 출시한다 우리은행은 지난달 22일 최고 금리가 연 3 20 인 2022 우리 특판 정기예금 을 2조원 한도로 내놨는데 6일 만에 팔렸다 같은 달 28일 한도를 두 배인 1조2000억원으로 늘렸다 하지만 1일 현재 한도까지 1437억원만 남아 두 번째 소진이 임박했다 지난달 17일 케이뱅크가 출시한 연 5 0 금리의 코드K 자유적금 10만 계좌도 10일 만에 모두 소진됐다 6월 두 차례 선보인 5 대 금리 적금 특판에 덕분에 수신이 한 달 사이 8500억원 늘자 케이뱅크는 7월에도 특판 상품 출시를 계획하고 있다
0.5442991256713867 경제와이드 모닝벨 조간 브리핑 장연재 조간브리핑입니다 발길 끊는 개미들 거래대금 20개월만에 최저 동학개미들이 국내 주식시장을 떠나고 있다는 기사 먼저 보겠습니다 중앙일보입니다 미국발 금리 인상과 세계 경제 침체 우려로 올해에만 코스피가 20 넘게 급락하자 개인투자자들이 증시를 이탈하고 있습니다 코스피에서 개인 투자자의 하루 평균 거래 대금은 4조 3 009억 원으로 2년 4개월 만에 최저 수준을 기록했습니다 증시 대기자금인 투자자예탁금은 지난달 말 기준 반년 만에 10조 원이 줄었고 빚을 내 투자한 후 아직 갚지 않은 금액인 신용거래융자 잔고도 같은 기간 5조 원 이상 줄었습니다 이런 가운데 당분간 전 세계의 경기 침체 공포로 국내증시 반등을 기대하긴 어렵다는 의견이 지배적인데요 반면 일부 증권가에서는 기존 악재가 반영된 만큼 약세장을 오히려 기회로 삼아야 한다는 의견도 있습니다 지방 중심 역전세 깡통아파트 확산 경향신문 기사입니다 최근 지방의 저가 아파트를 중심으로 전세가격이 매매가격보다 높은 역전세 현상이 나타나고 있습니다 정부의 다주택자 규제 완화 조치 이후 매물이 쌓이고 있지만 금리가 오르자 집을 사려는 사람이 없어 집값은 하락하고 있습니다 반면 전세시장은 신규 계약체결 시점에 경신까지 염두에 두고 4년 치 상승분을 미리 가격에 반영하려는 경향이 있어서 역전세가 발생하고 있는 건데요 전세계약 시점에 집값이 이미 전세가격보다 낮다면 보증금을 보호받을 수 없어서 문제가 되고 있습니다 이런 현상은 현재까지 갭투자가 주로 이뤄지는 3억 원 이하 지방 저가 아파트에서 주로 나타나는데요 전문가들은 서울 집값은 큰 변화가 없기 때문에 전국적인 문제로 보기는 어렵다고 분석했습니다 경기 침체에 빅테크 감원 시작됐다 전 세계 기업에 감원 공포가 불고 있다는 조선일보 기사도 보겠습니다 코로나 팬데믹 기간 큰돈을 벌며 조직 규모를 키웠던 테크 기업들 너도나도 긴축 경영에 돌입하고 있습니다 인플레이션과 금리 인상 등으로 사업 환경이 급속도로 악화되고 있기 때문입니다 페이스북은 올해 신규 채용을 당초 계획보다 30 줄이기로 했고 테슬라는 정규직의 10 인 6 000여 명에 대해 해고를 예고했습니다 중국 빅테크 기업인 텐센트도 올 상반기 전체 인력의 10 15 인력을 감축했습니다 국내 대기업들도 타격이 불가피해 보이는데요 네이버는 올해 신규 채용을 작년보다 30 정도 줄인다는 계획입니다 수주 늘어도 속타는 조선업 설계인력 6년새 70 급감 매일경제 신문 기사입니다 13년여 만에 최대 수주 실적을 이어가고 있는 한국 조선 산업이 이중의 인력 부족 현상을 겪고 있습니다 당장 올해 하반기 늘어나는 건조 물량을 소화해낼 생산 인력이 부족하고 미래 성장 동력을 이끌 설계 연구개발 부문 인력도 과거의 절반 이하로 최저 수준을 유지하고 있습니다 장기간 지속된 불황으로 조선업계는 다른 산업 현장에 비해 처우가 낮고 불황 호황에 따른 온도 차가 커 고용 안정성이 낮은 탓입니다 결국 장기간 지속된 보릿고개 여파가 국내 조선 산업의 현재 미래 모두 발목을 잡고 있다는 우려가 커지고 있습니다 벌써 37 8도 찜통 장맛비 내릴 때까지 더위 견뎌야 한겨레 기사입니다 어제 3일 참 많이 더웠죠 서울 낮 최고 기온이 올여름 들어 가장 높은 34 2도를 기록했고 경기 시흥시 신형동에서 37 8도가 측정되는 등 전국이 폭염으로 몸살을 앓았습니다 폭염은 모레인 6일까지 이어질 것으로 보입니다 제4호 태풍 에어리 가 한반도를 비껴갔지만 고온다습한 공기가 유입되면서 강한 햇볕과 높은 습도에 의해 체감온도가 크게 오르고 있기 때문인데요 오늘 전국 대부분 지역에 폭염특보가 발효된 가운데 최고 체감온도가 35도 안팎까지 오르고 밤사이 열대야가 나타나는 곳이 있겠습니다 이번 더위는 물러났던 장맛비가 7일께 다시 찾아오면 한풀 꺾일 것으로 보입니다
0.5419588088989258 금융지주 및 은행 리스크 시나리오별 영향 분석 은행권 자기자본 확대 위해 채권 발행 증자 배당 축소 등 고심할 듯 금융감독원 전경 금감원 제공 금융감독원이 은행권에 대한 스트레스 테스트 재무건전성 평가 에 나섰다 물가 금리 인상 등 대내외 금융시장의 불확실성이 커지는 상황에서 손실에 대응할 수 자본력을 갖췄는지 국내 은행의 기초체력을 파악하기 위한 조치다 4일 금융당국에 따르면 금감원은 지난달 말 KB 신한 하나 우리 NH농협 등 5대 금융지주 등 은행 19곳에 스트레스 테스트에 필요한 자료를 제출하도록 요구한 것으로 확인됐다 스트레스 테스트는 2 3주가량 소요될 예정이다 금감원 관계자는 은행에 스트레스 테스트 자료를 요청하는 자료를 보냈다 며 금융시장의 불확실성 속에서 지킬 수 있는 체력이 어느 정도인지 빨리 파악하는 게 중요하다고 생각해 스트레스 테스트를 진행하는 것 이라고 말했다 금감원이 유가 환율 금리 등 거시경제 지표의 변화를 가정한 시나리오를 주면 은행은 신용자산 자본비율 대손충당금 이자손익 당기순이익 등에 미치는 영향을 자체적으로 분석해서 제출하게 된다 또 다른 금감원 관계자는 바텀업 Boom up 방식으로 은행에 정해준 시나리오를 주고 이를 기초로 해서 스트레스 테스트를 한다 고 설명했다 이번 스트레스 테스트는 은행권의 손실흡수능력을 파악하기 위한 것이다 테스트 결과 위험성이 감지되면 대손충당금 규모를 재설정하는 등 손실흡수능력을 제고하기 위한 조치가 이뤄질 것으로 보인다 금감원은 이미 은행권에 부채 부실화에 대한 안전판을 마련하는 차원에서 충당금 확대를 주문하고 있다 이복현 금감원장은 미증유의 퍼펙트스톰 총체적 복합위기 이 점점 다가오는 모습이고 어쩌면 이미 시작됐을지도 모른다 면서 금리 상승과 자산 가격 조정 등에 따른 건전성 악화에도 대비해 금융사에 충분한 충당금을 쌓도록 하는 등 충격 흡수능력을 제고하고 있다 고 말한 바 있다 또한 이번 스트레스 테스트 결과에 따라 은행권의 자체적인 배당 정책도 영향을 받을 것으로 전망된다 다만 금감원은 지난해 배당 자제를 권고한 행정지도가 종료된 만큼 스트레스 테스트가 금융지주 및 은행의 배당 정책 결정과 연결되는 부분은 없다고 선을 그었다 금감원 관계자는 행정지도가 끝난 만큼 배당 축소를 강제하는 상황은 아니다 고 말했다 김소영 금융위원회 부위원장 역시 지난 5월 금리 배당 등 가격 변수의 자율성을 최대한 보장해 금융산업의 디지털 혁신과 발전을 적극 지원하겠다 고 말한 바 있다 금융당국이 배당에 자율성을 보장했지만 시장 불확실성에 따른 대손충당금 추가 적립이 강력하게 요구되고 있어 은행권 스스로 배당을 자제할 가능성이 있다 은행이 대출 부실 가능성이 커지는 가운데 당국의 요청에 따라 손실흡수능력을 제고하기 위해선 국제결제은행 BIS 자기자본비율을 끌어올려야 한다 이를 위해선 자기자본을 확대해야 하는데 은행은 통상 후순위채 발행 증자 등의 방식을 택한다 그러나 최근 채권과 증권 시장 모두 상황이 좋지 않아 이익잉여금 중에서 배당으로 가는 부분을 줄이는 방법을 내놓을 수 있다 은행이 고금리 상황에서 예대금리차에 따른 이윤을 확보한 만큼 배당을 유지할 수 있다는 의견도 나왔다 한 금융 전문가는 은행에 있어 고금리는 예대마진이 늘어나 이자 수익이 많이 늘어나는 반면 부실이 늘어 돈을 못 갚는 차주들이 늘어난다는 양면이 있다 며 최근 은행이 이자 장사를 한다는 비판을 받을 정도로 은행별 상황은 나쁘지 않아 배당을 줄이지 않아도 될 것으로 보인다 고 말했다 은행권은 올해 상반기 역대 최대 실적을 다시 경신할 것으로 보인다 금융정보업체 에프앤가이드 등에 따르면 올해 상반기 4대 금융지주의 순이익은 8조9798억원으로 추산됐다 이는 지난해 상반기 최대 실적으로 기록된 8조910억원을 뛰어넘는 규모다
0.5307894349098206 한국부동산원 시계열 통계 분석 강남 용산 경기 외곽 나홀로 상승 노도강 비롯 강북권이 하락 주도 하반기 하락 압력 더 높아질 것 서울 잠실 일대 아파트 단지 박종식 기자 anaki hani co kr 금리 인상과 대출 규제 경기침체 우려가 겹치면서 올해 상반기 서울 수도권 아파트값이 3년 만에 고개를 숙인 것으로 조사됐다 그러나 이른바 똘똘한 한채 고가 아파트 가 몰려있는 서울 강남권과 대통령실이 이전한 용산은 다른 곳과 달리 아파트값이 소폭 상승해 대조를 보였다 시장에선 금리가 가파르게 오르는데다 소비 위축과 경기 침체 우려가 높아진 하반기에는 전반적으로 집값 하락 압력이 더 거세질 것으로 내다보고 있다 5일 한국부동산원의 주간 아파트값 동향 시계열 통계 를 보면 올해 1월3일 대비 지난달 27일 현재 서울 아파트 매맷값은 0 21 하락했고 전세가는 0 32 내린 것으로 집계됐다 수도권 전체로는 매매값이 0 43 내렸고 전셋값은 0 61 하락했다 이처럼 서울 수도권의 반기 단위 아파트값이 일제히 떨어진 것은 지난 2019년 상반기 이후 3년 만에 처음이다 올해 상반기 서울에선 강북권이 아파트 매맷값 하락을 이끌었다 성북구가 0 89 를 기록한 것을 비롯해 서대문 0 68 노원 0 62 은평 0 52 강북 0 51 도봉 0 47 구 등 차례로 낙폭이 컸다 중저가 아파트 밀집지역인 이른바 노도강 노원 도봉 강북구 의 하락세도 뚜렷했다 금리 인상과 함께 올해 1월부터 시행된 차주 단위 디에스아르 DSR 총부채원리금상환비율 대출 규제 영향이 수요 위축으로 이어진 것으로 보인다 이와 달리 강남권 아파트값은 강세였다 서초 0 53 강남 0 27 구의 매맷값이 오르면서 상반기 동남권 강남 서초 송파 강동 매맷값은 평균 0 13 상승한 것으로 집계됐다 윤석열 정부가 올해 1가구1주택자 종합부동산세를 2020년 수준으로 되돌리기로 하면서 고가주택의 감세 혜택이 상대적으로 커진 점이 영향을 끼친 것으로 풀이된다 대통령실 이전으로 개발 기대감이 높아진 용산구 0 34 도 아파트값이 올라 강남권과 어깨를 나란히 했다 경기도에서는 과천 1 02 용인 1 17 시흥 2 65 화성 2 63 의왕 1 23 등 지난해 집값 상승폭이 컸던 곳들이 하락세를 주도했다 그러나 지난해 경기도 아파트 매맷값이 광역급행철도 GTX 호재 등으로 연간 20 32 급등했던 것에 견주면 올해 상반기 평균 낙폭 0 53 은 미미한 수준이다 또 지난해와 달리 올해 상반기에는 경기도 외곽지역인 이천 6 10 여주 0 83 안성 1 69 파주 1 58 등의 아파트값이 상승해 눈길을 끌었다 시장에서는 올해 하반기에는 아파트값 하락 압력이 더 높아질 것으로 본다 금리가 더 가파르게 오를 것으로 예상되는데다 물가 인상과 경기침체가 겹치는 스태그플레이션 우려도 커지고 있기 때문이다 건설산업연구원은 최근 내놓은 2022년 하반기 주택 부동산 경기전망 보고서에서 올해 하반기 수도권 집값 주택종합 매매가격 은 0 5 지방은 0 7 내릴 것으로 전망했다 김성환 건설산업연구원 경제금융연구실 부연구위원은 물가 상승률 임금 상승률 등과 비교할 때 현재 집값은 수요자들이 감당하기 어려운 수준 이라며 대출 규제 금리 인상 등 여러 요인이 겹치며 현재 가격 수준을 유지할 수 있는 동력이 약해지고 있다 고 진단했다 일반 수요자들도 하반기 집값 하락을 점치는 의견이 많다 부동산R114가 최근 실시한 2022년 하반기 주택가격 전망 조사에서 응답자 2275명 의 38 2 는 하락 을 예상했고 상승 전망은 24 3 에 그쳤으며 보합 이 37 5 를 차지했다 이는 지난 2019년 상반기 조사 이후 약 3년 만에 하락 전망이 상승 전망을 앞지른 결과라는 게 부동산R114의 설명이다
0.5200155973434448 기사내용 요약 가계대출 잔액 699조6521억원 금리상승 자산시장 주춤 영향 하반기 규제 강화에 증가 전환 어려울 듯 서울 뉴시스 이주혜 기자 국내 주요 은행의 가계대출 잔액이 올해 상반기 감소한 것으로 나타났다 6개월간 9조원 이상이 줄었다 특히 신용대출이 8조원 넘게 줄면서 가계대출 감소세를 이끈 것으로 분석됐다 1일 은행권에 따르면 KB국민 신한 하나 우리 NH농협은행의 지난달 말 기준 가계대출 잔액은 699조6521억원으로 전월보다 1조4094억원 감소했다 가계대출 잔액이 700조원대 아래로 떨어진 것은 지난해 8월 이후 약 10개월 만이다 가계대출은 올해 1월부터 6개월 연속 감소세를 지속하면서 반년간 9조4008억원이 줄었다 은행권 관계자는 상반기 대출 감소는 금리 영향이 제일 크다고 볼 수 있다 며 자산시장도 상승세를 멈추면서 대출을 받아서 투자하는 수요가 사라졌다 실수요자가 아니면 대출을 받지 않는 분위기 라고 설명했다 주택담보대출은 지난달 소폭 늘면서 한 달 만에 증가했다 지난달 말 기준 주담대 잔액은 506조7714억원로 전월보다 991억원 늘었다 올해 들어 지난달까지 6개월간 주담대 잔액은 1조3668억원 늘어난 것으로 나타났다 지난해 하반기에는 한 달에만 3조원 이상 4조원까지도 늘어난 것과 비교하면 증가세가 둔화한 것이다 전월에는 감소세를 보이기도 했다 신용대출은 지난해 12월부터 지난달까지 꾸준히 줄면서 가계대출 감소세를 견인했다 올해에만 8조8783억원이 줄었다 지난달 말 신용대출 잔액은 130조6789억원으로 전월보다 1조1204억원이 감소했다 감소폭은 전월 6613억원 보다 커졌다 지난해까지만 해도 낮은 금리와 자산시장의 높은 수익률에 대출을 통한 영끌 로 투자에 나선 이들이 많았지만 금리가 가파르게 오르고 자산시장이 침체하면서 신용대출도 감소세를 지속하고 있다 집단대출은 지난달 말 기준 159조9421억원으로 전월 보다 3412억원 늘었다 4개월 연속 증가세를 지속했다 전세대출은 5개월 연속 늘었다 전월 대비 4479억원 늘어난 132조9061억원으로 집계됐다 전세대출 잔액은 올해 상반기 3조2092억원 증가했다 시중은행 관계자는 전세대출은 실수요자 중심이기 때문에 금리가 올라도 필요한 사람은 대출을 받을 수밖에 없다 면서 전셋값이 오르면 대출도 늘어나게 된다 고 설명했다 금리 상승이 계속되고 대출 관련 규제가 강화되면서 하반기에도 가계대출 감소 분위기는 크게 바뀌기 어려울 전망이다 은행권 관계자는 7월부터 총부채원리금상환비율 DSR 규제가 강화되고 금리도 오르다 보니 대출이 늘어날 이유가 없는 것 같다 면서 실수요자 중심으로는 지금과 같은 분위기를 반전시키기는 어려울 것 이라고 말했다

### 실습하기
- 1. 내가 질문하려는 주제와 관련있는 데이터를 만들어 보세요
    - 예) 점심 메뉴 추천이다
        - 리스트에 점심 메뉴 관련 데이터를 데이터 프레임 형태로 만들어서 벡터화 시켜야 한다.
- 2. 질문을 해서 얼마나 잘 찾는지 확인해 봅시다.

In [8]:
sentence = [
    "점심 메뉴로 돈까스를 추천합니다.",
    "오늘 점심은 김치찌개를 추천합니다.",
    "든든한 점심으로 제육볶음이 좋습니다.",
    "국물 있는 점심 메뉴로 순두부찌개를 추천합니다.",
    "간단한 점심으로 짜장면이 좋습니다.",
    "가볍게 먹고 싶다면 샌드위치를 추천합니다.",
    "한식 점심 메뉴로 비빔밥을 추천합니다.",
    "매콤한 점심 메뉴로 닭갈비가 좋습니다.",

    "저녁에 볼 만한 영화를 추천할 수 있습니다.",
    "파이썬은 예제를 직접 작성하면서 공부하는 것이 좋습니다.",
    "인공지능 개발은 다양한 모델을 실험해 볼 수 있는 분야입니다.",
    "주말 여행지로 가까운 바다나 산을 추천합니다."
]

passage_vecs = model.encode(
    ["passage: " + text for text in sentence],
    normalize_embeddings=True
)

In [9]:
query = "오늘 점심 뭐 먹을까?"

query_vec = model.encode(
    "query: " + query,
    normalize_embeddings=True
)

In [15]:
# 사용자가 입력한 질문과 의미가 비슷한 문장을 검색하는 함수
# query : 사용자가 입력한 검색 문장
# k     : 유사도가 높은 결과를 몇 개 출력할지 지정
def search_text_2(query, k=3):

    # 사용자의 질문에 "query: "를 붙여 임베딩 벡터로 변환
    # normalize_embeddings=True:
    # 벡터의 크기를 정규화해서 코사인 유사도 계산에 사용하기 좋게 만듦
    query_vec = model.encode(
        "query: " + query,
        normalize_embeddings=True
    )

    # 사용자의 질문 벡터와
    # 미리 만들어둔 답변 데이터(passage_vecs)의 유사도를 계산
    similarity = util.cos_sim(query_vec, passage_vecs)

    # 유사도가 높은 순서대로 정렬한 후
    # 상위 k개의 인덱스만 가져옴
    for i in similarity[0].argsort(descending=True)[:k]:

        # PyTorch Tensor 값을 일반 정수형으로 변환
        index = i.item()

        # 유사도 점수와 해당 문장을 출력
        print(
            similarity[0][index].item(),  # 유사도 점수
            sentence[index]               # 해당 인덱스의 원본 문장
        )

In [16]:
search_text_2("매운거? ")

0.45003312826156616 가볍게 먹고 싶다면 샌드위치를 추천합니다.
0.44601067900657654 주말 여행지로 가까운 바다나 산을 추천합니다.
0.44386008381843567 매콤한 점심 메뉴로 닭갈비가 좋습니다.

In [17]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "dragonkue/BGE-m3-ko",
    device="cpu"
)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\study-with-ai\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Playdata\.cache\huggingface\hub\models--dragonkue--BGE-m3-ko. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/201 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/31.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/698 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.36k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

## beg-m3 접두어없이 데이터와 query(질문) 을 구성하셔야 합니다.

In [25]:
df['passage_add'] = df['정제본문']
df.head()

,제목,본문,카테고리,요약,출처URL,정제본문,passage_add
0,현대백화점그룹 더현대 광주 추진,서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복...,경제,"6 6일 현대백화점그룹이 광주시에 문화복합몰을 만든다고 6일 밝혔으며, 광주시는 서...",https://n.news.naver.com/mnews/article/001/001...,서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복...,서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복...
1,이스타항공 이상직 회사와 무관…오해 살 언동 말아야,전주 뉴시스 김얼 기자 이스타항공 자금 배임·횡령으로 전주교도소에 수감됐었던 이상직...,경제,이이스항공은 자금 배임·횡령으로 전주교도소에 수감됐었던 이상직 전 의원이 출소한 것...,https://n.news.naver.com/mnews/article/003/001...,전주 뉴시스 김얼 기자 이스타항공 자금 배임 횡령으로 전주교도소에 수감됐었던 이상직...,전주 뉴시스 김얼 기자 이스타항공 자금 배임 횡령으로 전주교도소에 수감됐었던 이상직...
2,농협은행 농협금융 출범 10주년 기념주화 NFT 이벤트,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 ‘10주년 기념주...,경제,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 소셜미디어 인스타...,https://n.news.naver.com/mnews/article/366/000...,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 10주년 기념주화...,NH농협은행은 올해 농협금융 출범 10주년을 맞아 이달 29일까지 10주년 기념주화...
3,오늘부터 유류세 인하 폭 확대…하반기 바뀌는 세제·금융 정책은,img tag s 지난 30일 서울의 한 주유소. 〈사진 연합뉴스〉 img tag ...,경제,정부는 고유가 상황에 따라 국민의 유류비 부담 완화를 위해 이날부터 유류세를 법정 ...,https://n.news.naver.com/mnews/article/437/000...,img tag s 지난 30일 서울의 한 주유소 사진 연합뉴스 img tag e 오...,img tag s 지난 30일 서울의 한 주유소 사진 연합뉴스 img tag e 오...
4,푸르덴셜생명 더 큰 드림 변액연금보험Ⅱ에 신규펀드 13종 추가,파이낸셜뉴스 푸르덴셜생명보험은 급변하는 금융시장에 대응하기 위해 무배당 더 큰 드림...,경제,지난르덴셜생명보험은 급변하는 금융시장에 대응하기 위해 무배당 더 큰 드림 변액연금보...,https://n.news.naver.com/mnews/article/014/000...,파이낸셜뉴스 푸르덴셜생명보험은 급변하는 금융시장에 대응하기 위해 무배당 더 큰 드림...,파이낸셜뉴스 푸르덴셜생명보험은 급변하는 금융시장에 대응하기 위해 무배당 더 큰 드림...

In [26]:
article_vec = model.encode(df['passage_add'].tolist()[:100], normalize_embeddings=True)
print(article_vec)

KeyboardInterrupt:

In [27]:
alticle_vecs = model.encode(
    df['passage_add'].tolist()[:100],
    normalize_embeddings=True,
    batch_size=4
)

In [28]:
def search_text(query, k=3):
    query_vec = model.encode(
        "query: " + query,
        normalize_embeddings=True
    )

    similarity = util.cos_sim(query_vec, article_vec)

    for i in similarity[0].argsort(descending=True)[:k]:
        index = i.item()

        print(
            similarity[0][index].item(),
            df["정제본문"].iloc[index]
        )

In [30]:
query = "오늘 점심메뉴 뭐야?"
search_text(query)

0.19991737604141235 서울 연합뉴스 현대백화점그룹이 광주광역시에 서울 여의도 더현대 서울 과 같은 문화복합몰을 만든다고 6일 밝혔다

In [35]:
# 사용자가 입력한 질문과 의미가 비슷한 문장을 검색하는 함수
# query : 사용자가 입력한 검색 문장
# k     : 유사도가 높은 결과를 몇 개 출력할지 지정
def search_text_2(query, k=3):

    # 사용자의 질문에 "query: "를 붙여 임베딩 벡터로 변환
    # normalize_embeddings=True:
    # 벡터의 크기를 정규화해서 코사인 유사도 계산에 사용하기 좋게 만듦
    query_vec = model.encode(
        query,
        normalize_embeddings=True
    )

    # 사용자의 질문 벡터와
    # 미리 만들어둔 답변 데이터(passage_vecs)의 유사도를 계산
    similarity = util.cos_sim(query_vec, passage_vecs)

    # 유사도가 높은 순서대로 정렬한 후
    # 상위 k개의 인덱스만 가져옴
    for i in similarity[0].argsort(descending=True)[:k]:

        # PyTorch Tensor 값을 일반 정수형으로 변환
        index = i.item()

        # 유사도 점수와 해당 문장을 출력
        print(
            similarity[0][index].item(),  # 유사도 점수
            sentence[index]               # 해당 인덱스의 원본 문장
        )

In [40]:
sentence = [
    "점심 메뉴로 돈까스를 추천합니다.",
    "오늘 점심은 김치찌개를 추천합니다.",
    "든든한 점심으로 제육볶음이 좋습니다.",
    "국물 있는 점심 메뉴로 순두부찌개를 추천합니다.",
    "간단한 점심으로 짜장면이 좋습니다.",
    "가볍게 먹고 싶다면 샌드위치를 추천합니다.",
    "한식 점심 메뉴로 비빔밥을 추천합니다.",
    "매콤한 점심 메뉴로 닭갈비가 좋습니다.",

    "저녁에 볼 만한 영화를 추천할 수 있습니다.",
    "파이썬은 예제를 직접 작성하면서 공부하는 것이 좋습니다.",
    "인공지능 개발은 다양한 모델을 실험해 볼 수 있는 분야입니다.",
    "주말 여행지로 가까운 바다나 산을 추천합니다."
]

passage_vecs = model.encode(
    [ text for text in sentence],
    normalize_embeddings=True,
    batch_size=4
)

In [38]:
search_text_2("매운거? ")

0.4569898247718811 가볍게 먹고 싶다면 샌드위치를 추천합니다.
0.4475945234298706 매콤한 점심 메뉴로 닭갈비가 좋습니다.
0.3715878427028656 국물 있는 점심 메뉴로 순두부찌개를 추천합니다.